#!/usr/bin/env python3
import csv,hashlib,json,math
from pathlib import Path
OUT='docs/vm_tlb/review_packs/C16_CROSS_OPERATOR_HANDOFF_HEADROOM_QUALIFICATION_V1'
FIELDS=['candidate_id','model_deployment_scenario','phase','layer_semantic_operator','producer_identity','intermediate_identity','consumer_identity','runtime_implementation','shape_dtype','launch_count','natural_ordering','concurrency','evidence_source','identity_confidence','timing_authority','unknown_fields']
def wt(p,f,rows):
 with p.open('w',newline='') as h:w=csv.DictWriter(h,fieldnames=f,delimiter='\t',lineterminator='\n');w.writeheader();[w.writerow({k:'NA' if r.get(k) is None else r.get(k) for k in f}) for r in rows]
def sha(x):return hashlib.sha256(x).hexdigest()
def main():
 r=Path.cwd();o=r/OUT;o.mkdir(parents=True,exist_ok=True)
 census=[
 {'candidate_id':'QWEN7B_FFN_GATE_UP_ACTMUL_DOWN','model_deployment_scenario':'Qwen2.5-7B-Instruct-AWQ accepted natural decode D1-D3','phase':'DECODE','layer_semantic_operator':'28 layers gate/up/SiLU-mul/down FFN','producer_identity':'gate_proj and up_proj WQLinear_GEMM','intermediate_identity':'FP16 gate/up outputs and SiLU(gate)*up product','consumer_identity':'down_proj WQLinear_GEMM','runtime_implementation':'separate PyTorch modules/elementwise ops; no accepted persistent fused FFN','shape_dtype':'B1 decode; intermediate width 18944 FP16','launch_count':'84 linear modules/decode plus elementwise UNKNOWN','natural_ordering':'gate/up then activation-multiply then down; exact wall window not archived','concurrency':'gate/up overlap UNKNOWN','evidence_source':'C16_E1_OPERATOR_FAMILY_EXPANSION_CONSUMER_174NEW_V1/INDEPENDENT_ALL_FFN_ANALYSIS.json','identity_confidence':'HIGH_SEMANTIC_MEDIUM_PHYSICAL','timing_authority':'WEIGHT_AUTHORITY_LIMITED: run-aligned module-duration sum, not pair-window union','unknown_fields':'physical copy/alias details; elementwise kernel rows; producer-start to last-consumer wall window'},
 {'candidate_id':'QWEN_ATTENTION_QKV_ROPE_KV_CORE','model_deployment_scenario':'accepted Qwen/Qwen3 natural attention evidence','phase':'DECODE','layer_semantic_operator':'attention projection/RoPE/KV update/attention core','producer_identity':'Q/K/V projections','intermediate_identity':'Q/K/V and rotated/cache representations','consumer_identity':'attention core','runtime_implementation':'library attention paths vary by accepted anchor','shape_dtype':'authority-dependent','launch_count':'UNKNOWN unified natural pair count','natural_ordering':'semantic order known; wall union unavailable','concurrency':'UNKNOWN','evidence_source':'Qwen3 attention/KV accepted review packs','identity_confidence':'MEDIUM','timing_authority':'WEIGHT_AUTHORITY_LIMITED','unknown_fields':'exact physical materialization; pair window; overlap'},
 {'candidate_id':'AWQ_GEMM_TO_SPLIT_REDUCTION','model_deployment_scenario':'accepted low-bit module/natural-shape evidence','phase':'DECODE module','layer_semantic_operator':'W4 GEMM partial planes to sum reduction','producer_identity':'gemm_forward_4bit m16n128k32 split8','intermediate_identity':'FP16 [8,M,N] scratch','consumer_identity':'sum(0) reduction','runtime_implementation':'accepted split8','shape_dtype':'FP16 scratch','launch_count':'GEMM+reduction','natural_ordering':'strict sequential dependency','concurrency':'none','evidence_source':'split-K/grouped accepted lineage','identity_confidence':'HIGH','timing_authority':'MODULE/NCU available but branch CLOSED','unknown_fields':'none material to qualification'},
 {'candidate_id':'AWQ_DEQUANT_TO_MMA','model_deployment_scenario':'strong GROUP_FULL_M split1 source-compatible target','phase':'W4 GEMM','layer_semantic_operator':'packed weight dequant/layout to MMA','producer_identity':'register unpack+affine dequant','intermediate_identity':'FP16 B_shared operand tile','consumer_identity':'ldmatrix/MMA','runtime_implementation':'register->CTA B_shared->register, grouped CTA mapping','shape_dtype':'K32xN128 INT4+metadata to FP16','launch_count':'one per CTA K32 iteration','natural_ordering':'inside one kernel','concurrency':'two warps cooperate','evidence_source':'C16_LOWBIT_DATAFLOW_SCREEN_V1 and conversion headroom pack','identity_confidence':'HIGH','timing_authority':'natural SHARE3 f=0.0173998 is shape-compatible family bound only','unknown_fields':'cross-CTA physical issue lifetime'},
 {'candidate_id':'OLMOE_ROUTER_EXPERT_COMBINE','model_deployment_scenario':'OLMoE accepted natural routing','phase':'DECODE','layer_semantic_operator':'router to expert MLP to weighted combine','producer_identity':'gate/router','intermediate_identity':'top8 ids/weights and expert outputs','consumer_identity':'expert dispatch/combine','runtime_implementation':'OlmoeSparseMoeBlock expert loop','shape_dtype':'BF16, top8','launch_count':'routing records available','natural_ordering':'semantic sequence known','concurrency':'UNKNOWN','evidence_source':'C16_OLMOE routing accepted packs','identity_confidence':'HIGH_ROUTING_MEDIUM_HANDOFF','timing_authority':'WEIGHT_AUTHORITY_LIMITED','unknown_fields':'non-double-counted pair window; materialization; overlap'}]
 wt(o/'CANDIDATE_CENSUS.tsv',FIELDS,census)
 baseline=[
 {'candidate_id':'QWEN7B_FFN_GATE_UP_ACTMUL_DOWN','strong_baseline':'current vendor/AWQ modules; no accepted fused/persistent FFN comparison','major_cost_already_eliminated':'NO_PROOF','residual_status':'AUTHORITY_AND_BASELINE_GAP','decision':'INSUFFICIENT_AUTHORITY'},
 {'candidate_id':'QWEN_ATTENTION_QKV_ROPE_KV_CORE','strong_baseline':'library attention/RoPE/KV fast paths present but heterogeneous','major_cost_already_eliminated':'UNKNOWN','residual_status':'NO_COMMON_PAIR_AUTHORITY','decision':'INSUFFICIENT_AUTHORITY'},
 {'candidate_id':'AWQ_GEMM_TO_SPLIT_REDUCTION','strong_baseline':'GROUP_FULL_M split1 direct output','major_cost_already_eliminated':'YES','residual_status':'SPLIT/GROUPED_BRANCH_CLOSED','decision':'STOP_STRONG_SOFTWARE_ALREADY_SUFFICIENT'},
 {'candidate_id':'AWQ_DEQUANT_TO_MMA','strong_baseline':'register dequant + CTA B_shared staging; grouped mapping','major_cost_already_eliminated':'CTA-internal full-tile duplication eliminated','residual_status':'cross-CTA duplicate exists but expanded/sync cost high; QUICK/StreamDQ near neighbors','decision':'STOP_STRONG_SOFTWARE_ALREADY_SUFFICIENT'},
 {'candidate_id':'OLMOE_ROUTER_EXPERT_COMBINE','strong_baseline':'native expert loop; no accepted matched fused baseline','major_cost_already_eliminated':'UNKNOWN','residual_status':'TIMING_AUTHORITY_LIMITED','decision':'INSUFFICIENT_AUTHORITY'}]
 wt(o/'STRONG_BASELINE_AUDIT.tsv',list(baseline[0]),baseline)
 costs=[
 {'candidate_id':'QWEN7B_FFN_GATE_UP_ACTMUL_DOWN','intermediate_bytes':'per layer gate/up each 37888 B; product 37888 B logical','materialization_bytes':'UNKNOWN physical write/read count','read_write_count':'UNKNOWN accepted raw','producer_layout':'FP16 module output','consumer_layout':'down_proj FP16 input','lifetime':'within one FFN layer','fanout':'1 down_proj','alias_view':'UNKNOWN','physical_copy':'LIKELY separate tensors but not receipt-closed','evidence_status':'LIMITED'},
 {'candidate_id':'AWQ_GEMM_TO_SPLIT_REDUCTION','intermediate_bytes':'split8 [8,M,N] FP16','materialization_bytes':'accepted exact scratch sizes','read_write_count':'GEMM writes + reduction reads','producer_layout':'8 partial planes','consumer_layout':'sum reduction','lifetime':'GEMM to reduction','fanout':'1','alias_view':'NO','physical_copy':'YES','evidence_status':'CLOSED_BUT_STRONG_BASELINE_REMOVES'},
 {'candidate_id':'AWQ_DEQUANT_TO_MMA','intermediate_bytes':'8192 B strict FP16 B tile','materialization_bytes':'CTA-private B_shared','read_write_count':'one shared write + ldmatrix reads','producer_layout':'FP16 transposed B_shared','consumer_layout':'MMA register fragment','lifetime':'one K32 CTA iteration; cross-CTA UNKNOWN','fanout':'two warps within CTA; 2-4 CTA cross-group','alias_view':'NO','physical_copy':'shared-memory staging','evidence_status':'SOURCE_CLOSED'}]
 wt(o/'HANDOFF_COST_EVIDENCE.tsv',list(costs[0]),costs)
 f_ffn=0.445746799882408;f_share3=0.017399766619420998
 ceilings=[
 {'candidate_id':'QWEN7B_FFN_GATE_UP_ACTMUL_DOWN','weight_fraction':f_ffn,'weight_basis':'84 selected module-duration sum / decode; NOT pair wall-clock union','zero_pair_ceiling':1/(1-f_ffn),'zero_pair_status':'OPTIMISTIC_UPPER_BOUND_NOT_ADMISSION_WEIGHT','T_materialize_upper':'UNKNOWN','S_materialize_local':'UNKNOWN','S_materialize_decode':'UNKNOWN','S_overlap_local':'UNKNOWN','S_overlap_decode':'UNKNOWN','overlap_status':'PERFECT_OVERLAP_NOT_WELL_DEFINED','gate':'G0_FAIL'},
 {'candidate_id':'QWEN_ATTENTION_QKV_ROPE_KV_CORE','weight_fraction':None,'weight_basis':'no legal wall-clock union','zero_pair_ceiling':None,'zero_pair_status':'NOT_COMPUTABLE','T_materialize_upper':'UNKNOWN','S_materialize_local':'UNKNOWN','S_materialize_decode':'UNKNOWN','S_overlap_local':'UNKNOWN','S_overlap_decode':'UNKNOWN','overlap_status':'PERFECT_OVERLAP_NOT_WELL_DEFINED','gate':'G0_FAIL'},
 {'candidate_id':'AWQ_GEMM_TO_SPLIT_REDUCTION','weight_fraction':None,'weight_basis':'module evidence; family branch closed','zero_pair_ceiling':None,'zero_pair_status':'NOT_NEEDED_STRONG_BASELINE','T_materialize_upper':'accepted but eliminated by split1','S_materialize_local':'strong baseline measured','S_materialize_decode':'UNKNOWN natural union','S_overlap_local':'NOT_APPLICABLE','S_overlap_decode':'NOT_APPLICABLE','overlap_status':'STRICT_DEPENDENCY','gate':'STOP_STRONG_SOFTWARE'},
 {'candidate_id':'AWQ_DEQUANT_TO_MMA','weight_fraction':f_share3,'weight_basis':'accepted natural SHARE3 target share; shape-compatible family bound','zero_pair_ceiling':1/(1-f_share3),'zero_pair_status':'OPTIMISTIC_UPPER_BOUND','T_materialize_upper':'UNKNOWN exclusive critical cost','S_materialize_local':'UNKNOWN','S_materialize_decode':'UNKNOWN','S_overlap_local':'UNKNOWN','S_overlap_decode':'UNKNOWN','overlap_status':'in-kernel dependency; cross-CTA handoff not present','gate':'G1_STOP'},
 {'candidate_id':'OLMOE_ROUTER_EXPERT_COMBINE','weight_fraction':None,'weight_basis':'no wall-clock authority','zero_pair_ceiling':None,'zero_pair_status':'NOT_COMPUTABLE','T_materialize_upper':'UNKNOWN','S_materialize_local':'UNKNOWN','S_materialize_decode':'UNKNOWN','S_overlap_local':'UNKNOWN','S_overlap_decode':'UNKNOWN','overlap_status':'PERFECT_OVERLAP_NOT_WELL_DEFINED','gate':'G0_FAIL'}]
 wt(o/'ORACLE_CEILINGS.tsv',list(ceilings[0]),ceilings)
 fam=[{'family_id':'QWEN7B_ALL_FFN_LINEAR_SUM','members':'gate/up/down x28','union_authority':'module-duration sum only; not producer-start to last-consumer wall union','fraction_or_bound':f_ffn,'zero_cost_ceiling_or_bound':1/(1-f_ffn),'status':'OPTIMISTIC_UPPER_BOUND_NOT_ADMISSIBLE'},{'family_id':'SHARE3_UP_PROJECTION','members':'3 accepted natural up targets','union_authority':'run-aligned target share','fraction_or_bound':f_share3,'zero_cost_ceiling_or_bound':1/(1-f_share3),'status':'G1_STOP_SUB2_PERCENT'}]
 wt(o/'FAMILY_AGGREGATION.tsv',list(fam[0]),fam)
 (o/'TOP_CANDIDATES.md').write_text('# Top candidates\n\n1. **Qwen7B FFN gate/up→activation/multiply→down** has the largest optimistic kernel-sum bound (~1.804x), but fails G0: no non-double-counted pair wall-clock union, no exclusive materialization cost, and no accepted matched strong fusion baseline. It is not Lane7-ready.\n2. **AWQ dequant→MMA** has strict source identity, but accepted natural SHARE3 zero-cost ceiling is only ~1.0177x and CTA-internal staging already removes major duplication; STOP.\n3. Attention and OLMoE handoffs remain timing-authority limited.\n\nNo candidate meets the revised EARLY_NATIVE_ORACLE_GATE six requirements; no early gate file is emitted.\n')
 decision={'schema_version':1,'decision':'INSUFFICIENT_AUTHORITY','early_native_oracle_gate_emitted':False,'final_admission':'EARLY_ORACLE_NOT_ADMITTED','reason_zh':'最高表面headroom的FFN链缺少合法pair wall-clock union、exclusive materialization成本和matched strong baseline；其余候选要么低于2% zero-cost gate，要么已被强软件路径解决或timing authority不足。','qualified_candidate_count':0,'gpu_used':False,'lane4_partial_accessed':False}
 (o/'FINAL_DECISION.json').write_text(json.dumps(decision,indent=2,sort_keys=True)+'\n');(o/'README.md').write_text('# C16 cross-operator handoff headroom qualification\n\nCPU-only candidate census and oracle ceilings. Final: insufficient authority; no EARLY gate and no Lane7 contract.\n');(o/'SHA256SUMS').write_text('')
 files=sorted(x for x in o.iterdir() if x.is_file() and x.name!='SHA256SUMS');(o/'SHA256SUMS').write_text('\n'.join(f'{sha(x.read_bytes())}  {x.name}' for x in files)+'\n')
if __name__=='__main__':main()
