#!/usr/bin/env python3
import csv,hashlib,json
from pathlib import Path
OUT='docs/vm_tlb/review_packs/C16_FFN_HANDOFF_AUTHORITY_RECOVERY_V1'
def wt(p,f,rows):
 with p.open('w',newline='') as h:w=csv.DictWriter(h,fieldnames=f,delimiter='\t',lineterminator='\n');w.writeheader();[w.writerow({k:'UNKNOWN' if r.get(k) is None else r.get(k) for k in f}) for r in rows]
def sha(x):return hashlib.sha256(x).hexdigest()
def main():
 r=Path.cwd();o=r/OUT;o.mkdir(parents=True,exist_ok=True)
 layers=[]
 for i in range(28):layers.append({'layer_id':i,'scenario':'accepted Qwen2.5-7B natural decode GUD84/D1-D3','gate_proj_identity':'semantic module timing available','up_proj_identity':'semantic module timing available','activation_identity':'source graph only; GPU correlation unavailable','multiply_identity':'source graph only; GPU correlation unavailable','down_proj_identity':'semantic module timing available','t_start_gpu_ns':None,'t_end_gpu_ns':None,'T_ffn_window_ms':None,'gate_up_overlap':None,'other_gpu_work_inside_window':None,'stream_overlap':None,'module_duration_sum_ms':None,'window_minus_duration_sum_ms':None,'status':'NATURAL_FFN_TIMELINE_AUTHORITY_INSUFFICIENT'})
 wt(o/'FFN_LAYER_TIMELINE.tsv',list(layers[0]),layers)
 union=[{'metric':'module_duration_sum','value_fraction':0.445746799882408,'value_ms':None,'authority':'run-aligned 84 linear-module CUDA-event duration sum','status':'AVAILABLE_NOT_WALL_CLOCK_UNION'},{'metric':'FFN_window_union','value_fraction':None,'value_ms':None,'authority':'no Qwen per-layer GPU start/end/correlation timeline','status':'NOT_COMPUTABLE'},{'metric':'FFN_exclusive_or_attributable_time','value_fraction':None,'value_ms':None,'authority':'overlap/exclusive attribution unavailable','status':'NOT_COMPUTABLE'}]
 wt(o/'FFN_WINDOW_UNION.tsv',list(union[0]),union)
 data=[
 {'object':'gate_proj output','producer':'gate_proj WQLinear_GEMM','consumer':'SiLU and multiply','logical_shape':'B1x1x18944','dtype':'FP16 accepted AWQ input/output path','bytes':37888,'global_write':'UNKNOWN without correlated GPU activity','global_read':'UNKNOWN','layout':'contiguous module output expected by graph; physical layout receipt absent','read_write_count':None,'must_materialize':None,'fusion_possible':'source graph permits activation fusion in principle','already_fused':'NOT_PROVEN'},
 {'object':'up_proj output','producer':'up_proj WQLinear_GEMM','consumer':'multiply','logical_shape':'B1x1x18944','dtype':'FP16','bytes':37888,'global_write':'UNKNOWN','global_read':'UNKNOWN','layout':'physical receipt absent','read_write_count':None,'must_materialize':None,'fusion_possible':'gate/up joint input path possible in other implementations','already_fused':'NO_ACCEPTED_EVIDENCE'},
 {'object':'SiLU result','producer':'activation','consumer':'multiply','logical_shape':'B1x1x18944','dtype':'FP16/compute semantics source-bound; physical dtype UNKNOWN','bytes':37888,'global_write':'UNKNOWN','global_read':'UNKNOWN','layout':'UNKNOWN','read_write_count':None,'must_materialize':None,'fusion_possible':'activation+multiply commonly fusible','already_fused':'UNKNOWN_CURRENT_RUNTIME'},
 {'object':'multiply result / down input','producer':'SiLU(gate)*up','consumer':'down_proj WQLinear_GEMM','logical_shape':'B1x1x18944','dtype':'FP16 accepted down input','bytes':37888,'global_write':'UNKNOWN','global_read':'UNKNOWN','layout':'down input semantic tensor; physical handoff unknown','read_write_count':None,'must_materialize':None,'fusion_possible':'persistent/fused FFN capability exists in neighbors','already_fused':'NO_ACCEPTED_MATCHED_EVIDENCE'}]
 wt(o/'FFN_HANDOFF_DATAFLOW.tsv',list(data[0]),data)
 baselines=[{'baseline':'current accepted Qwen2.5 AWQ runtime','semantic_match':'YES','available_on_RTX4080':'YES','gate_up_joint_kernel':'NO_ACCEPTED_EVIDENCE','activation_multiply_fused':'UNKNOWN','down_persistent_with_producer':'NO_ACCEPTED_EVIDENCE','status':'BASELINE_IDENTITY_CLOSED_HANDOFF_OPTIMIZATION_UNKNOWN'},{'baseline':'AutoAWQ/Marlin/QUICK family','semantic_match':'PARTIAL_OR_NO','available_on_RTX4080':'implementation-dependent','gate_up_joint_kernel':'capability neighbor only','activation_multiply_fused':'capability neighbor only','down_persistent_with_producer':'not accepted for exact current semantics','status':'NEAREST_NEIGHBOR_NOT_RUNNABLE_MATCHED_BASELINE'},{'baseline':'Kitsune/VTC/ComFuse/Rubin capabilities','semantic_match':'NO_DIRECT_MATCH','available_on_RTX4080':'NO_OR_UNQUALIFIED','gate_up_joint_kernel':'general capability','activation_multiply_fused':'general capability','down_persistent_with_producer':'general capability','status':'RELATED_WORK_BOUNDARY_ONLY'}]
 wt(o/'FFN_STRONG_BASELINE_AUDIT.tsv',list(baselines[0]),baselines)
 ceilings=[{'oracle':'F0 whole-FFN zero-cost','local_or_decode_value':1/(1-0.445746799882408),'basis':'84 module-duration sum fraction','status':'OPTIMISTIC_UPPER_BOUND_NOT_LEGAL_WALL_UNION'},{'oracle':'F0 legal window union','local_or_decode_value':None,'basis':'T_ffn_union unavailable','status':'NOT_COMPUTABLE'},{'oracle':'F1 free materialization','local_or_decode_value':None,'basis':'exclusive materialization/critical-path upper bound unavailable','status':'MATERIALIZATION_CEILING_NOT_IDENTIFIABLE'},{'oracle':'F2 perfect overlap','local_or_decode_value':None,'basis':'multi-stage DAG lacks correlated stage times/fill-drain authority','status':'PERFECT_OVERLAP_NOT_WELL_DEFINED'}]
 wt(o/'FFN_ORACLE_CEILINGS.tsv',list(ceilings[0]),ceilings)
 gaps='''# Authority gaps\n\nThe accepted Qwen natural authority provides run-aligned CUDA-event module-duration sums and decode wall timing, but not a correlated GPU timeline for gate/up/activation/multiply/down. No accepted artifact contains per-layer GPU start/end, CUDA correlation IDs and semantic NVTX bindings sufficient to reconstruct producer-start→last-consumer windows. Existing NSYS census artifacts belong to other deployments and preserve operator/layer as UNKNOWN at capture time. Therefore the 44.5747% sum cannot be converted into an FFN window union. Physical intermediate writes/reads and exclusive materialization time also remain unknown.\n''';(o/'AUTHORITY_GAPS.md').write_text(gaps)
 contract={'schema_version':1,'status':'PROPOSED_NOT_AUTHORIZED','reason_old_authority_insufficient':'missing Qwen per-layer correlated GPU activity for gate/up/SiLU/multiply/down and decode wall interval','scenario':{'must_reuse':'exact accepted Qwen2.5-7B natural GUD84 decode scenario/input/model/runtime','new_model':False,'kernel_changes':False},'capture_only':['one decode wall NVTX interval','per-layer semantic NVTX ranges for gate_proj/up_proj/SiLU/multiply/down_proj','CUDA kernel start/end, stream and correlation IDs','CPU NVTX-to-CUDA correlation','minimal run identity and timestamps'],'tools':{'NSYS':'lightweight cuda,nvtx activity only','NCU':False,'NVBit':False,'SASS':False,'oracle':False},'after_capture_enables':['FFN_LAYER_TIMELINE','non-double-counted FFN window union','F0 legal hard ceiling','assessment whether F1/F2 can be isolated'],'scientific_identity_change':'none; annotations/timeline only','stop_rules':['hook/annotation changes output or kernel selection','semantic correlation incomplete','decode wall interval missing'],'gpu_execution_requires_project_review':True}
 (o/'MINIMAL_FFN_TIMELINE_CAPTURE_CONTRACT.json').write_text(json.dumps(contract,indent=2,sort_keys=True)+'\n')
 decision={'schema_version':1,'decision':'NEEDS_MINIMAL_TIMELINE_CAPTURE','natural_timeline_status':'NATURAL_FFN_TIMELINE_AUTHORITY_INSUFFICIENT','module_duration_sum_fraction':0.445746799882408,'optimistic_nonadmissible_zero_cost_ceiling':1/(1-0.445746799882408),'legal_ffn_union_fraction':None,'F1':'MATERIALIZATION_CEILING_NOT_IDENTIFIABLE','F2':'PERFECT_OVERLAP_NOT_WELL_DEFINED','early_native_oracle_gate_emitted':False,'lane7_oracle_contract_emitted':False,'gpu_used':False,'lane4_partial_accessed':False}
 (o/'FINAL_DECISION.json').write_text(json.dumps(decision,indent=2,sort_keys=True)+'\n');(o/'README.md').write_text('# C16 FFN handoff authority recovery\n\nCPU-only audit. Result: existing natural authority cannot recover legal FFN wall-clock windows; a minimal timeline capture contract is proposed but not authorized.\n')
 files=sorted(x for x in o.iterdir() if x.is_file() and x.name!='SHA256SUMS');(o/'SHA256SUMS').write_text('\n'.join(f'{sha(x.read_bytes())}  {x.name}' for x in files)+'\n')
if __name__=='__main__':main()
