#!/usr/bin/env python3
import csv,hashlib,json,math,statistics,subprocess
from pathlib import Path
OUT='docs/vm_tlb/review_packs/C16_LOWBIT_CONVERSION_REUSE_HEADROOM_174NEW_V1'
LIT='4db73af069aae32c0b3eb91313930a04a46a9123';GROUP='a3a36e64ae4a3a316df2bf4dfc9cac95caf8e164';STATIC='c72d28b17247f25d0c3613604ab6cab1737666e0'
def blob(r,c,p):return subprocess.check_output(['git','show',f'{c}:{p}'],cwd=r)
def sha(x):return hashlib.sha256(x).hexdigest()
def wt(p,f,rows):
 with p.open('w',newline='') as h:w=csv.DictWriter(h,fieldnames=f,delimiter='\t',lineterminator='\n');w.writeheader();[w.writerow({k:'NA' if x.get(k) is None else x.get(k) for k in f}) for x in rows]
def target(name,m):
 mt=math.ceil(m/16);nt=12288//128;kt=4096//32;nall=mt*nt*kt;nu=nt*kt
 return {'target':name,'M':m,'K':4096,'N':12288,'mapping':'GROUP_FULL_M','split':1,'M_tiles':mt,'N_tiles':nt,'K32_tiles':kt,'N_all_cta_conversion_tiles':nall,'N_unique_strict_conversion_tiles':nu,'R_dup':1-nu/nall,'encoded_qweight_bytes_per_identity':2048,'encoded_qzeros_bytes_per_identity':64,'encoded_scales_bytes_per_identity':256,'encoded_total_bytes_per_identity':2368,'decoded_fp16_bytes_per_identity':8192,'consumer_ctas_per_identity':mt,'logical_producer_to_last_consumer_block_distance':mt-1,'minimum_shared_live_bytes':8192,'one_Ntile_full_K_decoded_bytes':kt*8192,'whole_operator_decoded_bytes':nu*8192}
def main():
 r=Path.cwd();o=r/OUT;o.mkdir(parents=True,exist_ok=True)
 auth={'literature':('docs/vm_tlb/literature_notes/c16/rounds/2026-09-29_LR10_REPRESENTATION_REUSE_AND_HANDOFF_COSTS.md',LIT),'dataflow':('docs/vm_tlb/review_packs/C16_LOWBIT_DATAFLOW_SCREEN_V1/DATAFLOW_EVIDENCE.tsv','HEAD'),'grouped_strong':('docs/vm_tlb/review_packs/C16_GROUPED_RESIDUAL_PARALLELISM_CONSUMER_174NEW_V1/FINAL_DECISION.json',GROUP),'static_mapping':('docs/vm_tlb/review_packs/C16_SPLITK_FOOTPRINT_STATIC_AUDIT_174NEW_V1/ADDRESS_MAPPING.md',STATIC)}
 audit={k:{'commit':c,'path':p,'sha256':sha(blob(r,c,p))} for k,(p,c) in auth.items()};(o/'AUTHORITY_AUDIT.json').write_text(json.dumps({'status':'PASS_CPU_ONLY','sources':audit,'gpu_used':False,'lane4_partial_accessed':False,'splitk_grouped_branch_closed':True},indent=2,sort_keys=True)+'\n')
 rows=[target('DISCOVERY_STRONG_GROUPED_M64',64),target('VALIDATION_FROZEN_GROUPED_M32',32)];wt(o/'DUPLICATION_SCOPE.tsv',list(rows[0]),rows)
 scopes=[{'scope':'warp','raw_duplicate_ratio':None,'existing_elimination':'two warps cooperatively produce one CTA-private B_shared tile; full-tile per-warp duplication is not present','remaining_strict_duplicate_ratio':0.0,'limitation':'per-thread fragment-level duplication not dynamically counted'},{'scope':'CTA','raw_duplicate_ratio':0.0,'existing_elimination':'register unpack/affine result is staged once into CTA-private B_shared then consumed by ldmatrix/MMA','remaining_strict_duplicate_ratio':0.0,'limitation':'single-buffer barriers; no cross-CTA visibility'},{'scope':'CTA_GROUP_M64','raw_duplicate_ratio':0.75,'existing_elimination':'none across CTA-private shared memories','remaining_strict_duplicate_ratio':0.75,'limitation':'logical block adjacency is not physical issue-order proof'},{'scope':'WHOLE_OPERATOR_M64','raw_duplicate_ratio':0.75,'existing_elimination':'grouped ordering shortens logical distance only','remaining_strict_duplicate_ratio':0.75,'limitation':'reuse requires inter-CTA publication, synchronization and fanout'}];wt(o/'EXISTING_ELIMINATION.tsv',list(scopes[0]),scopes)
 buffers=[{'scope':'one strict conversion tile','encoded_bytes':2368,'expanded_bytes':8192,'consumer_count':4,'lifetime':'logical four-CTA group; exact cycles UNKNOWN','simultaneous_live_bytes':8192,'fanout':'4 CTA consumers; inter-CTA synchronization required'},{'scope':'one Ntile full K','encoded_bytes':303104,'expanded_bytes':1048576,'consumer_count':4,'lifetime':'128 K32 conversions across one Ntile','simultaneous_live_bytes':1048576,'fanout':'tile streaming or 1MiB materialization'},{'scope':'whole operator B representation','encoded_bytes':26148864,'expanded_bytes':100663296,'consumer_count':4,'lifetime':'whole GEMM','simultaneous_live_bytes':100663296,'fanout':'impractical as one on-chip live object; exceeds 64MiB L2'}];wt(o/'BUFFER_LIFETIME.tsv',list(buffers[0]),buffers)
 amd=json.loads((r/'docs/vm_tlb/review_packs/C16_E1_SHARED_RESIDENCY_DESIGN_REVIEW_174NEW_V1/SHARED_STAGE_AMDAHL_AUDIT.json').read_text());f=float(amd['three_target_share']['median']);ar=[]
 for sl in (1.05,1.1,1.25,1.5,2.0,4.0):ar.append({'scope':'accepted natural SHARE3 up-projection targets','f':f,'S_local':sl,'S_decode':1/((1-f)+f/sl),'S_zero_cost':1/(1-f),'authority':'SHARED_STAGE_AMDAHL_AUDIT three_target_share median','boundary':'Amdahl ceiling; grouped synthetic target is shape-compatible but not same natural shape'})
 wt(o/'AMDAHL_CEILINGS.tsv',list(ar[0]),ar)
 (o/'CONVERSION_IDENTITY.md').write_text('# Strict conversion identity\n\nIdentity = `(qweight K32×N128 logical range, qzeros G128/N128 range, FP16 scales G128/N128 range, AutoAWQ packed INT4 affine format, zero/scale decode semantics, FP16 target operand dtype, m16n128k32 transposed B_shared/ldmatrix operand layout, CUDA half2 rounding/packing semantics)`。仅相同qweight地址不足以判同。不同K32即使共享metadata也产生不同conversion result。\n')
 conclusion=f"strong GROUP_FULL_M split1中存在严格跨CTA重复：M64每个(Ntile,Ktile)转换4次、唯一1次，R_dup=75%；M32验证点R_dup=50%。现有kernel已通过register计算+B_shared staging消除CTA内主要重复，但没有跨CTA共享。剩余单tile展开8KiB，fanout 4 CTA；完整Ntile展开1MiB，whole operator展开96MiB并超过64MiB L2。更关键的是accepted natural SHARE3目标时间权重仅f={f:.6f}，即使目标零成本whole-decode ceiling也只有{1/(1-f):.6f}x。结合QUICK/FLUTE/StreamDQ等近邻与同步/分发成本，本问题有重复但当前系统headroom不足，不值得进入新dequant cache机制研究。"
 (o/'SCIENTIFIC_INTERPRETATION.md').write_text('# 科学解释\n\n'+conclusion+'\n');(o/'FINAL_DECISION.json').write_text(json.dumps({'schema_version':1,'strict_repeated_conversion_exists':True,'dominant_scope':'cross-CTA within grouped Ntile','discovery_target':'M64 K4096 N12288 GROUP_FULL_M split1','validation_target_frozen_before_oracle':'M32 K4096 N12288 GROUP_FULL_M split1','system_time_fraction_f':f,'zero_cost_decode_ceiling':1/(1-f),'decision_zh':'建议STOP：不进入dequant cache/硬件机制；重复存在但展开/同步成本高且whole-decode上限小','gpu_used':False},indent=2,sort_keys=True)+'\n');(o/'OPEN_ISSUES.md').write_text('# Open issues\n\n- 精确跨CTA lifetime需GPU调度证据，当前为UNKNOWN。\n- natural f来自同类SHARE3 up-projection，不与synthetic grouped shape完全匹配。\n- 未测local oracle；本轮不授权GPU。\n');(o/'README.md').write_text('# C16 low-bit conversion reuse qualification\n\nCPU-only问题资格与Amdahl headroom分析。结论：存在跨CTA严格重复，但建议STOP，不设计dequant cache。\n')
 files=sorted(x for x in o.iterdir() if x.is_file() and x.name!='SHA256SUMS');(o/'SHA256SUMS').write_text('\n'.join(f'{sha(x.read_bytes())}  {x.name}' for x in files)+'\n')
if __name__=='__main__':main()
