#!/usr/bin/env python3
from __future__ import annotations
import csv,hashlib,json,subprocess
from pathlib import Path
ROOT=Path('/data/c16/awma/uvm_oversubscription_pilot_20260926');REPO=Path('/home/huangrulin/workspace/worktrees/accel-sim-awma-uvm-pilot-v1');OUT=REPO/'docs/vm_tlb/review_packs/AWMA_AI_UVM_OVERSUBSCRIPTION_FEASIBILITY_PILOT_V1';OUT.mkdir(parents=True,exist_ok=True)
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def read(p):return list(csv.DictReader(open(p),delimiter='\t'))
def write(p,rows):
 with p.open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(rows[0]),delimiter='\t');w.writeheader();w.writerows(rows)
matrix=read(ROOT/'RUN_MATRIX.tsv');events=read(ROOT/'UVM_EVENT_MATRIX.tsv');steps=read(ROOT/'STEPWISE_BEHAVIOR.tsv');receipts=[json.loads(r['receipt_json']) for r in matrix if r['status']=='COMPLETE'];V=17171480576
cap=[
 {'capability':'cudaMallocManaged','status':'AVAILABLE','evidence':'64MiB probe PASS and 20GiB points COMPLETE'},
 {'capability':'cudaMemPrefetchAsync','status':'AVAILABLE','evidence':'probe GPU/CPU prefetch PASS; resident M1 points COMPLETE'},
 {'capability':'cudaMemAdvise set/unset read-mostly','status':'AVAILABLE','evidence':'probe return codes 0; not used in matrix'},
 {'capability':'cudaMemGetInfo','status':'AVAILABLE','evidence':'per-point before/after receipts'},
 {'capability':'NSYS UVM migration bytes/count/time','status':'AVAILABLE','evidence':'CUPTI_ACTIVITY_KIND_MEMCPY UVM_HTOD/UVM_DTOH with migrationCause'},
 {'capability':'NSYS/CUPTI GPU page-fault events/groups','status':'UNAVAILABLE','evidence':'no dedicated Unified Memory counter/activity table in exported SQLite'},
 {'capability':'CPU UVM page-fault telemetry','status':'UNAVAILABLE','evidence':'not exposed by selected NSYS trace configuration'},
 {'capability':'managed oversubscription stable execution','status':'AVAILABLE','evidence':'R2 and capped-R3 COMPLETE for P1/P2/P3'}]
write(OUT/'UVM_PLATFORM_CAPABILITY.tsv',cap)
min_margin=min(int(r['host_available_before'])-int(r['allocated_bytes']) for r in matrix if r['status']=='COMPLETE');max_gpu_delta=max(abs(x['gpu_free_before']-x['gpu_free_after']) for x in receipts)
safety=[{'physical_vram_bytes':V,'fixed_cap_bytes':20*1024**3,'r3_actual_ratio':min(20*1024**3,V*1.3)/V,'host_mem_total_bytes':67025514496,'host_mem_available_preflight_bytes':64858849280,'swap_total_bytes':8589930496,'minimum_host_margin_after_allocation_bytes':min_margin,'required_host_margin_bytes':8*1024**3,'max_inprocess_gpu_free_delta_after_cleanup_bytes':max_gpu_delta,'other_gpu_processes_preflight':'NONE','xid_or_reset_observed':'NO','status':'SAFETY_GATE_PASS'}]
write(OUT/'SYSTEM_SAFETY_RECEIPT.tsv',safety)
(OUT/'PATTERN_CONTRACT.md').write_text('''# Pattern contract\n\nAll patterns use one managed allocation and constant deterministic data with CPU-reference checksum closure.\n\n- **P1 DENSE_WEIGHT_STREAM:** 3 token-like steps; every step sequentially scans the full allocation.\n- **P2 KV_GROWTH:** 8 steps; each step GPU-writes a new 1/8 tail and scans the full monotonically growing prefix. This is KV-shaped, not attention.\n- **P3 MOE_EXPERT_ROTATION:** 64 equal expert regions, K=4, 16 steps. Experts `0,1` provide locality; rotating experts are `(7*step)%64` and `(7*step+13)%64`. This route is synthetic and not claimed to match OLMoE.\n\nM0 uses demand migration. M1 performs one full prefetch only for R0/R1; oversubscribed M1 is `NOT_APPLICABLE_OVERSUBSCRIBED`. Cold and immediate repeat are the only measured repetitions.\n''')
for name in ('MATRIX_PREREG.tsv','RUN_MATRIX.tsv','UVM_EVENT_MATRIX.tsv','STEPWISE_BEHAVIOR.tsv'):(OUT/name).write_bytes((ROOT/name).read_bytes())
checks=[
 {'check':'all_applicable_points_complete','status':'PASS','evidence':f"{sum(r['status']=='COMPLETE' for r in matrix)} COMPLETE; 6 oversubscribed-prefetch N/A"},
 {'check':'all_checksums','status':'PASS','evidence':f"{sum(x['checksum_pass'] for x in receipts)}/{len(receipts)}"},
 {'check':'runtime_cap','status':'PASS','evidence':'no measured point reached 180s'},
 {'check':'host_safety_margin','status':'PASS','evidence':str(min_margin)},
 {'check':'gpu_cleanup','status':'PASS_WITH_CONTEXT_RESIDUE_LIMIT','evidence':f'max in-process cudaMemGetInfo delta {max_gpu_delta} bytes; subsequent process starts recovered'},
 {'check':'driver_xid_reset','status':'PASS_NO_OBSERVED_EVENT','evidence':'all 18 applicable points and final nvidia-smi healthy'},
 {'check':'cold_repeat_interpretability','status':'PASS','evidence':'resident demand cold migration followed by stable repeat; oversubscribed P1/P2 repeat remains slow with eviction/remigration; P3 repeat stabilizes'}]
write(OUT/'STABILITY_CHECKS.tsv',checks)
(OUT/'AI_SHAPED_UVM_BEHAVIOR.md').write_text('''# AI-shaped UVM behavior\n\nStatus: `READY_FOR_AI_UVM_CHARACTERIZATION_V1`. Claims apply only to these deterministic synthetic patterns on RTX4080/Linux.\n\n- **P1 dense stream:** R0/R1 demand cold runs migrate approximately the allocation once and repeat becomes resident-fast. At R2/R3, HtoD traffic rises to about 113/129 GB and DtoH eviction to about 96/112 GB; repeat remains about 10/11 s. The full streamed set repeatedly thrashes once it exceeds VRAM.\n- **P2 growing prefix:** R0/R1 likewise stabilize after cold placement. R2/R3 produce about 109/123 GB HtoD and 92/107 GB DtoH; repeat remains about 9/11 s. Step data records the monotonic active-prefix transition rather than calling it real attention.\n- **P3 sparse expert rotation:** even at R2/R3, only selected expert regions are touched. HtoD is about 8.3/9.4 GB, DtoH about 2 MB, and immediate repeat is about 33/36 ms. It avoids the cyclic whole-pool thrash seen in P1/P2.\n- Resident M1 prefetch removes most cold-placement cost. Full prefetch is intentionally not applied under oversubscription.\n\nMigration memcpy telemetry is available and correlated to NVTX steps. Dedicated GPU/CPU page-fault counters are unavailable, so no fault-group count, TLB miss rate, PPN continuity, migration page-size, or shootdown claim is made. Synthetic access laws must not be represented as measured LLM or OLMoE behavior.\n''')
(OUT/'CLOSEST_WORK_SCREEN.md').write_text('''# Closest-work screen\n\n- Shao et al., *Oversubscribing GPU Unified Virtual Memory: Implications and Suggestions* (ICPE 2022), https://doi.org/10.1145/3489525.3511691 — closest ratio/access-pattern characterization and complex prefetch sensitivity; it does not establish these AI-shaped laws on this platform.\n- Kim et al., *Batch-Aware Unified Memory Management in GPUs* (ASPLOS 2020), https://hparch.gatech.edu/papers/kim-asplos20.pdf — analyzes fault batching and eviction scheduling; this pilot observes migration but proposes no scheduling mechanism.\n- Ganguly et al., *Adaptive Page Migration for Irregular Data-intensive Applications under GPU Memory Oversubscription* (IPDPS 2020), https://doi.org/10.1109/IPDPS47924.2020.00054 — distinguishes regular and sparse patterns and migration/zero-copy choices; P1/P2/P3 provide a bounded AI-shaped problem-discovery bridge only.\n- Jones et al., *HELM* (SC 2025), https://doi.org/10.1145/3712285.3759812 — closest telemetry-driven UVM characterization; this platform exposes migration memcpy but not dedicated fault counters.\n- Park et al., *Avatar* (MICRO 2024), https://www.cs.cmu.edu/~18742/papers/Park2024.pdf — studies speculative address translation and reports 130% oversubscription sensitivity. This pilot does not measure TLB behavior and cannot validate or refute Avatar.\n- NVIDIA, *Improving GPU Memory Oversubscription Performance*, https://developer.nvidia.com/blog/?p=37205 — platform guidance that access pattern and placement strongly affect oversubscription.\n''')
(OUT/'FUTURE_RESEARCH_QUESTIONS.md').write_text('''# Future research questions\n\n1. **Do real dense-weight and KV allocations exhibit the synthetic R1→R2 repeat-thrashing transition?** Evidence: P1/P2 move from resident-fast repeats to ~9–11 s repeats and >92 GB eviction at R2. AI property: whole-weight scans versus monotonic KV growth. Closest-work gap: prior UVM characterization is not bound to exact real-model tensor lifetimes. Validation: one instrumented local Llama run with explicitly managed weight/KV buffers, frozen tensor identities, migration bytes and per-step latency.\n2. **When does real MoE routing lose the sparse-residency advantage?** Evidence: P3 keeps R3 repeat near 36 ms with ~2 MB DtoH while P1/P2 thrash. AI property: K-of-N rotating experts with locality. Closest-work gap: generic irregular-access work does not bind routing entropy, expert size and reuse period. Validation: an OLMoE tensor-level UVM bridge varying only prerecorded routing traces and reporting expert-resident migration per decode step.\n''')
(OUT/'REAL_MODEL_BRIDGE_STATUS.md').write_text('# Real-model UVM bridge status\n\n`REAL_MODEL_UVM_BRIDGE_NOT_AVAILABLE_IN_PILOT`. No existing local path places an isolated PyTorch model tensor/buffer in CUDA Managed Memory without allocator replacement or substantial framework surgery. No bridge run or download was attempted.\n')
decision='READY_FOR_AI_UVM_CHARACTERIZATION_V1'
(OUT/'README.md').write_text(f'# AI UVM oversubscription feasibility pilot V1\n\nFinal status: `{decision}`. Managed oversubscription is stable; migration telemetry and timing are available, dedicated page-fault counters are not. P1/P2 thrash under R2/R3 while P3 sparse rotation remains stable. Results are synthetic-pattern observations, not real LLM behavior or a mechanism proposal.\n')
(OUT/'REPORT.md').write_text(f'# AWMA AI UVM Oversubscription Feasibility Pilot V1\n\nDecision: `{decision}`. Eighteen applicable cold/repeat points completed with checksum and cleanup gates; six oversubscribed prefetch controls were N/A by preregistration. Migration onset and qualitative differences are captured in `AI_SHAPED_UVM_BEHAVIOR.md`.\n')
(OUT/'OPTIONAL_REAL_MODEL_BRIDGE.tsv').write_text('status\nREAL_MODEL_UVM_BRIDGE_NOT_AVAILABLE_IN_PILOT\n')
# Durable receipts/index.
summary={'stage':'AWMA_AI_UVM_OVERSUBSCRIPTION_FEASIBILITY_PILOT_V1','status':decision,'physical_vram_bytes':V,'fixed_cap_bytes':20*1024**3,'complete_points':18,'not_applicable_points':6,'checksum_passes':18,'uvm_migration_rows':sum(int(r['migration_count'] or 0) for r in events),'uvm_migration_bytes':sum(int(r['migration_bytes'] or 0) for r in events),'gpu_fault_counter':'UNAVAILABLE','mechanism_proposed':False,'models_downloaded':False}
(ROOT/'FINAL_RECEIPT.json').write_text(json.dumps(summary,indent=2,sort_keys=True)+'\n')
rows=[]
for p in sorted(x for x in ROOT.rglob('*') if x.is_file() and x.name!='SHA256SUMS'):rows.append({'relative_path':str(p.relative_to(ROOT)),'size_bytes':p.stat().st_size,'sha256':sha(p)})
write(OUT/'RAW_DATA_INDEX.tsv',rows);(ROOT/'SHA256SUMS').write_text(''.join(f'{sha(p)}  {p.relative_to(ROOT)}\n' for p in sorted(x for x in ROOT.rglob('*') if x.is_file() and x.name!='SHA256SUMS')))
files=sorted(p for p in OUT.iterdir() if p.is_file());(OUT/'SHA256SUMS').write_text(''.join(f'{sha(p)}  {p.name}\n' for p in files))
(REPO/'docs/vm_tlb/codex_handoff/awma/AI_UVM_OVERSUBSCRIPTION_FEASIBILITY_PILOT_109_V1_REPORT.md').write_text(f'# AI UVM Oversubscription Feasibility Pilot 109 V1\n\nFinal status: `{decision}`. Safe fixed-ratio P1/P2/P3 runs reveal differentiated synthetic behavior and limited-but-reliable migration observability. No mechanism, model download or Accel-Sim run occurred.\n')
print(json.dumps(summary,sort_keys=True))
