#include <cuda_runtime.h>
#include <nvToolsExt.h>
#include <sys/sysinfo.h>
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <string>
#include <vector>

#define CK(x) do { cudaError_t e=(x); if(e!=cudaSuccess){fprintf(stderr,"CUDA_ERROR %s:%d %s\n",__FILE__,__LINE__,cudaGetErrorString(e)); return 2;} } while(0)
__global__ void sum_range(const uint32_t* a,uint64_t b,uint64_t e,unsigned long long* out){unsigned long long s=0;for(uint64_t i=b+blockIdx.x*blockDim.x+threadIdx.x;i<e;i+=(uint64_t)gridDim.x*blockDim.x)s+=a[i];atomicAdd(out,s);}
static constexpr uint32_t VALUE=0x01010101u;
__global__ void write_range(uint32_t* a,uint64_t b,uint64_t e){for(uint64_t i=b+blockIdx.x*blockDim.x+threadIdx.x;i<e;i+=(uint64_t)gridDim.x*blockDim.x)a[i]=VALUE;}
static uint64_t range_sum(uint64_t b,uint64_t e){return (e-b)*(uint64_t)VALUE;}
static uint64_t mem_avail(){std::ifstream f("/proc/meminfo");std::string k,u;uint64_t v;while(f>>k>>v>>u)if(k=="MemAvailable:")return v*1024;return 0;}
static void init_cpu(uint32_t* p,uint64_t n){memset(p,1,n*sizeof(uint32_t));}
static std::string arg(int argc,char**argv,const char*k,const char*d=""){for(int i=1;i+1<argc;i++)if(!strcmp(argv[i],k))return argv[i+1];return d;}
static void step_row(std::ofstream&f,const char*pat,const char*mode,const char*rep,int step,uint64_t active,int expert,float ms,uint64_t got,uint64_t exp){f<<pat<<'\t'<<mode<<'\t'<<rep<<'\t'<<step<<'\t'<<active<<'\t'<<expert<<'\t'<<ms<<'\t'<<got<<'\t'<<exp<<'\n';}
int main(int argc,char**argv){
 int dev=0;CK(cudaSetDevice(dev));cudaDeviceProp prop{};CK(cudaGetDeviceProperties(&prop,dev));int managed=0,concurrent=0,pageable=0;CK(cudaDeviceGetAttribute(&managed,cudaDevAttrManagedMemory,dev));CK(cudaDeviceGetAttribute(&concurrent,cudaDevAttrConcurrentManagedAccess,dev));CK(cudaDeviceGetAttribute(&pageable,cudaDevAttrPageableMemoryAccess,dev));
 if(std::string(arg(argc,argv,"--probe","0"))=="1"){
  const uint64_t bytes=64ull<<20,n=bytes/4;uint32_t*p=nullptr;unsigned long long*out=nullptr;size_t fb,tb;CK(cudaMemGetInfo(&fb,&tb));CK(cudaMallocManaged(&p,bytes));CK(cudaMallocManaged(&out,8));init_cpu(p,n);*out=0;cudaError_t adv1=cudaMemAdvise(p,bytes,cudaMemAdviseSetReadMostly,dev);cudaError_t adv2=cudaMemAdvise(p,bytes,cudaMemAdviseUnsetReadMostly,dev);cudaError_t pf1=cudaMemPrefetchAsync(p,bytes,dev);CK(pf1);CK(cudaDeviceSynchronize());sum_range<<<256,256>>>(p,0,n,out);CK(cudaDeviceSynchronize());uint64_t got=*out,exp=range_sum(0,n);cudaError_t pf2=cudaMemPrefetchAsync(p,bytes,cudaCpuDeviceId);CK(pf2);CK(cudaDeviceSynchronize());CK(cudaFree(out));CK(cudaFree(p));printf("{\"status\":\"UVM_PROBE_PASS\",\"device\":\"%s\",\"total_bytes\":%zu,\"free_before\":%zu,\"managedMemory\":%d,\"concurrentManagedAccess\":%d,\"pageableMemoryAccess\":%d,\"prefetch_gpu\":%d,\"prefetch_cpu\":%d,\"advise_set\":%d,\"advise_unset\":%d,\"checksum_pass\":%s}\n",prop.name,tb,fb,managed,concurrent,pageable,(int)pf1,(int)pf2,(int)adv1,(int)adv2,got==exp?"true":"false");return got==exp?0:3;
 }
 std::string pat=arg(argc,argv,"--pattern"),mode=arg(argc,argv,"--mode","M0"),outdir=arg(argc,argv,"--out");uint64_t bytes=std::stoull(arg(argc,argv,"--bytes"));uint64_t n=bytes/4;int steps=pat=="P1"?3:(pat=="P2"?8:16);uint32_t*p=nullptr;unsigned long long*out=nullptr;size_t free0,total0,free1,total1;uint64_t host0=mem_avail();CK(cudaMemGetInfo(&free0,&total0));CK(cudaMallocManaged(&p,bytes));CK(cudaMallocManaged(&out,8));init_cpu(p,n);*out=0;bool prefetched=false;if(mode=="M1"){if(bytes>free0){fprintf(stderr,"PREFETCH_NOT_APPLICABLE bytes=%llu free=%zu\n",(unsigned long long)bytes,free0);return 4;}CK(cudaMemPrefetchAsync(p,bytes,dev));CK(cudaDeviceSynchronize());prefetched=true;}
 std::ofstream sf(outdir+"/steps.tsv");sf<<"pattern\tmode\trepetition\tstep\tactive_bytes\texpert_id\tstep_ms\tchecksum\texpected\n";uint64_t all_got=0,all_exp=0;double wall_ms[2]={};float gpu_ms[2]={};uint64_t route_hash=1469598103934665603ull;
 for(int rep=0;rep<2;rep++){const char*rname=rep?"repeat":"cold";auto ws=std::chrono::steady_clock::now();cudaEvent_t a,b;CK(cudaEventCreate(&a));CK(cudaEventCreate(&b));CK(cudaEventRecord(a));for(int s=0;s<steps;s++){std::string label="UVM_PATTERN="+pat+";MODE="+mode+";REP="+rname+";STEP="+std::to_string(s);nvtxRangePushA(label.c_str());uint64_t got=0,exp=0,active=bytes;int expert=-1;*out=0;cudaEvent_t x,y;CK(cudaEventCreate(&x));CK(cudaEventCreate(&y));CK(cudaEventRecord(x));if(pat=="P1"){sum_range<<<256,256>>>(p,0,n,out);exp=range_sum(0,n);}else if(pat=="P2"){uint64_t e=n*(s+1)/steps,beg=n*s/steps;write_range<<<256,256>>>(p,beg,e);sum_range<<<256,256>>>(p,0,e,out);active=e*4;exp=range_sum(0,e);}else{const int E=64,K=4;uint64_t en=n/E;int ids[K]={0,1,(s*7)%E,(s*7+13)%E};active=en*4*K;for(int j=0;j<K;j++){uint64_t beg=en*ids[j],end=(ids[j]==E-1?n:beg+en);sum_range<<<256,256>>>(p,beg,end,out);exp+=range_sum(beg,end);route_hash=(route_hash^ids[j])*1099511628211ull;}expert=ids[2];}CK(cudaEventRecord(y));CK(cudaEventSynchronize(y));float ms;CK(cudaEventElapsedTime(&ms,x,y));got=*out;all_got+=got;all_exp+=exp;step_row(sf,pat.c_str(),mode.c_str(),rname,s,active,expert,ms,got,exp);CK(cudaEventDestroy(x));CK(cudaEventDestroy(y));nvtxRangePop();}CK(cudaEventRecord(b));CK(cudaEventSynchronize(b));CK(cudaEventElapsedTime(&gpu_ms[rep],a,b));wall_ms[rep]=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-ws).count();CK(cudaEventDestroy(a));CK(cudaEventDestroy(b));}
 CK(cudaDeviceSynchronize());CK(cudaFree(out));CK(cudaFree(p));CK(cudaDeviceSynchronize());CK(cudaMemGetInfo(&free1,&total1));uint64_t host1=mem_avail();bool pass=all_got==all_exp;printf("{\"status\":\"UVM_MATRIX_POINT_COMPLETE\",\"pattern\":\"%s\",\"mode\":\"%s\",\"bytes\":%llu,\"ratio\":%.8f,\"steps\":%d,\"prefetched\":%s,\"cold_gpu_ms\":%.6f,\"repeat_gpu_ms\":%.6f,\"cold_wall_ms\":%.6f,\"repeat_wall_ms\":%.6f,\"checksum_pass\":%s,\"checksum\":%llu,\"expected\":%llu,\"route_hash\":\"%016llx\",\"gpu_free_before\":%zu,\"gpu_free_after\":%zu,\"host_available_before\":%llu,\"host_available_after\":%llu}\n",pat.c_str(),mode.c_str(),(unsigned long long)bytes,(double)bytes/total0,steps,prefetched?"true":"false",gpu_ms[0],gpu_ms[1],wall_ms[0],wall_ms[1],pass?"true":"false",(unsigned long long)all_got,(unsigned long long)all_exp,(unsigned long long)route_hash,free0,free1,(unsigned long long)host0,(unsigned long long)host1);return pass?0:5;
}
