import csv,hashlib,json,platform
from pathlib import Path
import torch,transformers
root=Path('/data/c16/models/.incoming/deepseek_v2_lite/604d5664dddd88a0433dbae533b7fe9472482de0')
source_manifest=Path('/data/c16/models/.provenance/c16_recovery_v3/receipts/R1_DEEPSEEK_V2_LITE_ASSET_CONSOLIDATION/SOURCE_ENDPOINT_MANIFEST.json')
dest_manifest=Path('/data/c16/models/.provenance/c16_recovery_v3/receipts/R1_DEEPSEEK_V2_LITE_ASSET_CONSOLIDATION/DESTINATION_ENDPOINT_MANIFEST.json')
payload=Path('/data/c16/deepseek_v23/authority/deepseek-v2-lite__S2_TEXT.json')
out=Path('/data/c16/deepseek_v23r1/authority');out.mkdir(parents=True,exist_ok=True)
def sha(p):
 h=hashlib.sha256()
 with Path(p).open('rb') as f:
  for b in iter(lambda:f.read(1048576),b''):h.update(b)
 return h.hexdigest()
files=[]
for p in sorted(root.iterdir(),key=lambda x:x.name):
 if p.is_file():files.append({'relative_path':p.name,'size_bytes':p.stat().st_size,'sha256':sha(p)})
sm=json.loads(source_manifest.read_text());dm=json.loads(dest_manifest.read_text());src={x['filename']:{'size_bytes':x['size_bytes'],'sha256':x['sha256']} for x in sm['payloads']};dst={x['filename']:{'size_bytes':x['size_bytes'],'sha256':x['sha256']} for x in dm['payloads']};loc={x['relative_path']:{'size_bytes':x['size_bytes'],'sha256':x['sha256']} for x in files}
same=src==dst==loc;index=json.loads((root/'model.safetensors.index.json').read_text());weight_shards=[x for x in files if x['relative_path'].endswith('.safetensors') and x['relative_path'].startswith('model-')];tensor_total=index.get('metadata',{}).get('total_size')
manifest={'schema_version':1,'status':'DEEPSEEK_V23R1_STAGE0_AUTHORITY_REPAIRED_PASS' if same else 'FAIL','model_id':'deepseek-ai/DeepSeek-V2-Lite','revision':'604d5664dddd88a0433dbae533b7fe9472482de0','canonical_source_root':sm.get('root'),'local_destination_root':str(root),'canonical_manifest_file_count':len(files),'relative_file_set':[x['relative_path'] for x in files],'files':files,'deterministic_manifest_sha256':hashlib.sha256(json.dumps(files,sort_keys=True,separators=(',',':')).encode()).hexdigest(),'repository_payload_bytes':sum(x['size_bytes'] for x in files),'safetensors_file_bytes':sum(x['size_bytes'] for x in weight_shards),'safetensors_weight_shard_count':len(weight_shards),'safetensors_index_tensor_payload_bytes':tensor_total,'config_sha256':loc['config.json']['sha256'],'modeling_deepseek_sha256':loc['modeling_deepseek.py']['sha256'],'configuration_deepseek_sha256':loc['configuration_deepseek.py']['sha256'],'tokenizer_json_sha256':loc['tokenizer.json']['sha256'],'source_destination_local_exact_file_set_and_sha256_equal':same,'historical_v22_asset_bytes_scalar':31418842074,'verified_repository_payload_bytes':sum(x['size_bytes'] for x in files),'historical_metadata_drift_bytes':31418842074-sum(x['size_bytes'] for x in files),'source_manifest_sha256':sha(source_manifest),'destination_manifest_sha256':sha(dest_manifest)}
(out/'SUPERSEDING_ASSET_AUTHORITY.json').write_text(json.dumps(manifest,indent=2,sort_keys=True)+'\n')
pl=json.loads(payload.read_text());matrix=pl['token_ids'];tm=hashlib.sha256(json.dumps(matrix,separators=(',',':')).encode()).hexdigest()
rows=[['check','tier','expected_or_authority','actual','status','notes'],['model_revision','A','604d5664dddd88a0433dbae533b7fe9472482de0','604d5664dddd88a0433dbae533b7fe9472482de0','PASS','exact revision'],['relative_file_set','A','source manifest 15 paths','local 15 paths','PASS' if same else 'FAIL','source==destination==local'],['per_file_size_sha256','A','source/destination manifests','local full rehash','PASS' if same else 'FAIL','exact file authority'],['config_sha256','A','f346286b0f1c8b044252fd54cb4fa78b9fab6472a6e8bebb9edfe03d414ea03d',manifest['config_sha256'],'PASS' if manifest['config_sha256']=='f346286b0f1c8b044252fd54cb4fa78b9fab6472a6e8bebb9edfe03d414ea03d' else 'FAIL','config'],['custom_modeling_source_sha256','A','source/local manifest',manifest['modeling_deepseek_sha256'],'PASS','remote custom code identity'],['safetensors_index_and_shards','A','manifest identity','4 shards and index','PASS' if len(weight_shards)==4 else 'FAIL','required shards'],['input_payload_sha256','A','2ca11cff95f13bcdd0efcb3f5b2d6c0b8f7e30c9e67492d6b291362c09ff6935',sha(payload),'PASS' if sha(payload)=='2ca11cff95f13bcdd0efcb3f5b2d6c0b8f7e30c9e67492d6b291362c09ff6935' else 'FAIL','copied frozen bytes'],['canonical_token_matrix_sha256','A','14009279ed85b3de1f2510df84a3a8b2ba7a0d35f00c79d250d8e0e47cff63df',tm,'PASS' if tm=='14009279ed85b3de1f2510df84a3a8b2ba7a0d35f00c79d250d8e0e47cff63df' else 'FAIL','JSON token_ids matrix separators comma/colon'],['no_retokenization','A','frozen payload','no tokenizer invoked','PASS','V23 copied authority bytes'],['runtime_versions','B','pinned before deployment','python='+platform.python_version()+' torch='+torch.__version__+' transformers='+transformers.__version__,'RECORDED','must remain fixed during execution'],['aggregate_asset_bytes','C','historical V22 scalar 31418842074',str(manifest['repository_payload_bytes']),'DRIFT_RECORDED','not an identity gate'],['v1_v2_authority_label','C','V22 generic V2 label','V8 exact V1 source ref','DRIFT_RECORDED','exact source+payload controls V23R1']]
with (out/'STAGE0_GATE_AUDIT.tsv').open('w',newline='') as f:csv.writer(f,delimiter='\t',lineterminator='\n').writerows(rows)
reassess={'schema_version':1,'v23_decision':'C16_DEEPSEEK_V2_LITE_S2_PRODUCER_109_V23_BLOCKED_ASSET_BYTE_AUTHORITY_MISMATCH','v23r1_policy':'aggregate size is Tier C when exact file-set/per-file SHA Tier A closes','tier_a_closed':same and tm=='14009279ed85b3de1f2510df84a3a8b2ba7a0d35f00c79d250d8e0e47cff63df','decision':'DEEPSEEK_V23R1_STAGE0_AUTHORITY_REPAIRED_PASS' if same else 'FAIL'}
(out/'V23_BLOCKER_REASSESSMENT.json').write_text(json.dumps(reassess,indent=2,sort_keys=True)+'\n');print(json.dumps({'decision':reassess['decision'],'manifest_sha256':manifest['deterministic_manifest_sha256'],'bytes':manifest['repository_payload_bytes'],'token_matrix_sha256':tm},sort_keys=True))
if not same or tm!='14009279ed85b3de1f2510df84a3a8b2ba7a0d35f00c79d250d8e0e47cff63df':raise SystemExit(1)
