import csv,hashlib,json,shutil,subprocess
from pathlib import Path
wt=Path('/home/huangrulin/workspace/worktrees/accel-sim-deepseek-v26');base=Path('/data/c16/deepseek_v26');pack=wt/'docs/vm_tlb/review_packs/C16_DEEPSEEK_V2_LITE_PERSISTENT_MLA_109_V26'
if pack.exists():raise SystemExit('pack exists')
def sha(p):
 h=hashlib.sha256()
 with Path(p).open('rb') as f:
  for b in iter(lambda:f.read(1048576),b''):h.update(b)
 return h.hexdigest()
def cp(a,b):b.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(a,b)
pack.mkdir();(pack/'evidence').mkdir();(pack/'formal').mkdir();(pack/'ncu').mkdir()
for n in ['PERSISTENT_MLA_LIFETIME.json','PERSISTENT_MLA_STATE.pt','EXACT_STATE_CHAIN.json']:cp(base/'state'/n,pack/'evidence'/n)
for n in ['QK_REPLAY.json','QK_SIGNATURE.json','QK_static.tsv','QK_static.log','QK_FORMAL_AUDIT.json','qk_incontext.nsys-rep','qk_incontext.sqlite','qk_replay.nsys-rep','qk_replay.sqlite']:cp(base/n,pack/'evidence'/n)
cp(base/'QK_ncu.ncu-rep',pack/'ncu/QK_ncu.ncu-rep');cp(base/'QK_ncu.log',pack/'ncu/QK_ncu.log')
life=json.loads((base/'state/PERSISTENT_MLA_LIFETIME.json').read_text());audit=json.loads((base/'QK_FORMAL_AUDIT.json').read_text());rep=json.loads((base/'QK_REPLAY.json').read_text())
(pack/'UPSTREAM_AUTHORITY.json').write_text(json.dumps({'v23r1_head':'baf892ced6d66cbacabb995caf095e5280995097','model':'deepseek-ai/DeepSeek-V2-Lite@604d5664dddd88a0433dbae533b7fe9472482de0','input_payload_sha256':'2ca11cff95f13bcdd0efcb3f5b2d6c0b8f7e30c9e67492d6b291362c09ff6935','token_matrix_sha256':'14009279ed85b3de1f2510df84a3a8b2ba7a0d35f00c79d250d8e0e47cff63df'},indent=2,sort_keys=True)+'\n')
with (pack/'PERSISTENT_CACHE_OBJECTS.tsv').open('w',newline='') as f:
 w=csv.writer(f,delimiter='\t',lineterminator='\n');w.writerow(['decode_state','component','shape','dtype','stride','storage_ptr','storage_bytes','content_sha256','lifetime'])
 for state in ['cache_before_decode1','cache_after_decode1','cache_before_decode2','cache_after_decode2']:
  for comp,d in life[state].items():w.writerow([state,comp,d['shape'],d['dtype'],d['stride'],d['storage_ptr_hex'],d['storage_bytes'],d['sha256'],'cross-step persistent via prefix equality; update replaces storage'])
(pack/'PERSISTENT_CACHE_LIFETIME_AUDIT.json').write_text(json.dumps({'status':'PASS_MULTI_OBJECT_PERSISTENCE','objects':['DynamicCache.key_cache[0]','DynamicCache.value_cache[0]'],'lifetime':life,'update_semantics':'cache tensor storage is replaced on append while prior content persists as prefix across decode steps'},indent=2,sort_keys=True)+'\n')
flow={'typed_graph':['cache_before key/value -> cache.update -> cache_after key/value','cache_after key -> QK matmul key_transposed operand','cache_after value -> AV matmul value operand'],'qk_class':'MIXED_PERSISTENT_CACHE_CONSUMER','persistent_prefix_positions':2048,'current_append_positions':1,'direct_read_claim':'NO_CLEAN_SINGLE_OBJECT_DIRECT_READ: QK operand contains both persistent prefix and current append','derived_paths':['kv_b expansion is prior V23R1 DERIVED_BUFFER_READ/KV_B_EXPANSION_LATENT_READ']}
(pack/'MLA_PERSISTENT_TYPED_DATAFLOW.json').write_text(json.dumps(flow,indent=2,sort_keys=True)+'\n')
with (pack/'CONSUMER_CANDIDATE_MATRIX.tsv').open('w',newline='') as f:
 w=csv.writer(f,delimiter='\t',lineterminator='\n');w.writerow(['persistent_component','consumer','classification','retained','reason']);w.writerow(['key_cache[0] prefix','QK matmul','MIXED_PERSISTENT_CACHE_CONSUMER','YES','same-process prefix/current membership quantified']);w.writerow(['value_cache[0] prefix','AV matmul','MIXED_PERSISTENT_CACHE_CONSUMER','NO','second target not needed to establish multi-object topology']);w.writerow(['kv_b expansion','kv_b_proj','DERIVED_BUFFER_READ','NO','accepted V23R1 anchor, not persistent cache'])
(pack/'TARGET_SELECTION.json').write_text(json.dumps({'retained_targets':['layer0.self_attn.QK_matmul'],'evidence_class':'MIXED_PERSISTENT_CACHE_CONSUMER','clean_direct_target_found':False,'reason':'persistent key/value buffers include newly appended current-token segment at direct consumer boundary'},indent=2,sort_keys=True)+'\n');(pack/'REPLAY_SIGNATURES.json').write_text(json.dumps({'qk_replay':rep,'signature':json.loads((base/'QK_SIGNATURE.json').read_text())},indent=2,sort_keys=True)+'\n')
rows=list(csv.DictReader((base/'QK_static.tsv').open(),delimiter='\t'));(pack/'STATIC_PATH_AUDIT.json').write_text(json.dumps({'static_map_sha256':sha(base/'QK_static.tsv'),'static_instruction_count':len(rows),'direct_global_mref_count':sum(x['memory_space']=='GLOBAL' and x['has_mref']=='1' for x in rows),'ldgsts_count':sum(x['memory_space']=='GLOBAL_TO_SHARED' for x in rows),'generic_mref_count':sum(x['memory_space']=='GENERIC' and x['has_mref']=='1' for x in rows),'source_address_method':'actual SASS register-pair via v20_warp_regsource'},indent=2,sort_keys=True)+'\n');(pack/'DYNAMIC_CANARY_AUDIT.json').write_text(json.dumps(audit,indent=2,sort_keys=True)+'\n')
run='C16R_deepseek-v2-lite_s2-text_decode_nvbit-warp-mref-shard_v26-qk-mixed_20260917T130000Z_c26c26c26c26';ready=Path('/data/c16/capture/ready')/run
for n in ['RUN_MANIFEST.json','LOCAL_CLOSE_RECEIPT.json','WARP_SHARD_MANIFEST.json','QUICKCHECK.json']:cp(ready/n,pack/'formal'/n)
remote='hrl174new:/root/share/mnt164/huangrulin/c16_ai_workload'
for src,n in [(f'{remote}/receipts/{run}/VERIFICATION.json','VERIFICATION.json'),(f'{remote}/receipts/{run}/ADMISSION.json','ADMISSION.json'),(f'{remote}/reports/transfer_acks/{run}.TRANSFER_ACK.json','ACK.json')]:subprocess.run(['scp',src,str(pack/'formal'/n)],check=True)
with (pack/'FORMAL_TARGETS.tsv').open('w',newline='') as f:csv.writer(f,delimiter='\t',lineterminator='\n').writerows([['target','evidence_class','run_id','ack'],['layer0.self_attn.QK_matmul','MIXED_PERSISTENT_CACHE_CONSUMER',run,'PASS']])
(pack/'FORMAL_SUMMARY.json').write_text(json.dumps(audit,indent=2,sort_keys=True)+'\n');(pack/'ADMISSION_ACKS.json').write_text((pack/'formal/ACK.json').read_text());(pack/'NCU_TYPED_EVIDENCE.json').write_text(json.dumps({'status':'RAW_BOUNDED_REPORT_PRESERVED','report':'ncu/QK_ncu.ncu-rep','warning':'cache-control none; no normalized byte/cache-TLB causal claim'},indent=2,sort_keys=True)+'\n')
(pack/'SCIENTIFIC_INTERPRETATION.md').write_text(f'''# V26 interpretation\n\nDeepSeek MLA persistence is multi-object: key and value `DynamicCache` tensors persist logically across decode while append updates replace storage with enlarged tensors. QK directly reads the cache-after key object, but its operand has a 2048-position persistent prefix plus one just-appended current position. The admitted QK anchor therefore remains `MIXED_PERSISTENT_CACHE_CONSUMER`, never clean single-object direct-read evidence.\n\nV26 formal QK: {audit['static_direct_global_mref_count']} direct-GLOBAL static MREFs; {audit['executed_shards']} executed/{audit['zero_shards']} zero; {audit['active_lane_events']} active-lane events; overflow zero; ACK PASS. No cross-replay VA comparison, chronology, reuse distance, or cache/TLB causality claim is made.\n''')
(pack/'NEXT_STEP_AUTHORIZATION.json').write_text(json.dumps({'decision':'DEEPSEEK_PERSISTENT_MLA_DIRECT_READ_NOT_AVAILABLE_USE_TYPED_DERIVED_PATH','s3_execution_authorized_in_v26':False,'reason':'only mixed QK persistent/current cache consumer was defensibly isolated and admitted'},indent=2,sort_keys=True)+'\n');(pack/'FINAL_DECISION.json').write_text(json.dumps({'decision':'C16_DEEPSEEK_V2_LITE_PERSISTENT_MLA_109_V26_PASS_NO_DIRECT_READ_TARGET','formal_mixed_target_ack':'PASS','clean_direct_anchor':False},indent=2,sort_keys=True)+'\n');(pack/'OPEN_ISSUES.md').write_text('# Open issues\n\nA future S3 campaign must preserve the mixed persistent/current QK classification unless it can isolate a clean persistent-only consumer.\n')
items=[]
for f in sorted(pack.rglob('*')):
 if f.is_file() and f.name!='SHA256SUMS':items.append(f'{sha(f)}  {f.relative_to(pack).as_posix()}')
(pack/'SHA256SUMS').write_text('\n'.join(items)+'\n');print(pack)
