#!/usr/bin/env python3
"""Build deterministic, CPU-only C16 asset-readiness review artifacts."""
import argparse,csv,json,os,re,statistics,subprocess
from pathlib import Path
from qwen7_layer_inventory import inventory,residency,write_tsv,sha256,FIELDS
ROOT=Path('/root/share/mnt164/huangrulin/c16_ai_workload')
MODELS=[('llama-3.2-1b','Llama-3.2-1B'),('qwen2.5-0.5b-instruct','Qwen2.5-0.5B-Instruct'),('qwen2.5-7b-instruct-raw','Qwen2.5-7B-Instruct raw'),('qwen2.5-7b-instruct-awq','Qwen2.5-7B-Instruct-AWQ'),('qwen3-8b','Qwen3-8B'),('deepseek-v2-lite','DeepSeek-V2-Lite')]
def canon(v):return json.dumps(v,sort_keys=True,indent=2)+'\n'
def rows(path):
 with open(path,newline='',encoding='utf-8') as f:return list(csv.DictReader(f,delimiter='\t'))
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--out',required=True);a=ap.parse_args();out=Path(a.out);out.mkdir(parents=True,exist_ok=True)
 seed=ROOT/'provenance/catalog/C16_AUTHORITY_METADATA_SEED_V1';model_auth=rows(seed/'MODEL_AUTHORITY.tsv');input_auth=rows(seed/'INPUT_BINDING_AUTHORITY.tsv')
 auth={r['model_id']:r for r in model_auth}; asset=[]
 for slug,label in MODELS:
  dirs=sorted((ROOT/'assets/models'/slug).iterdir())
  if len(dirs)!=1:raise RuntimeError('FAIL_CLOSED: expected exactly one canonical revision for '+slug)
  d=dirs[0];receipt=json.loads((d/'MODEL_ARCHIVE_RECEIPT.json').read_text());m=auth[label];shards=sorted(d.glob('*.safetensors'))
  input_status=m['input_binding_status']
  if label=='Llama-3.2-1B':input_status='FUTURE_ADOPTED_S0_AUTHORITY_NOT_HISTORICAL_RECOVERY'
  asset.append({'canonical_slug':slug,'model_id':m['model_revision'].split('@')[0],'exact_revision':receipt['revision'],'canonical_path':str(d),'archive_receipt_path':str(d/'MODEL_ARCHIVE_RECEIPT.json'),'archive_receipt_sha256':sha256(d/'MODEL_ARCHIVE_RECEIPT.json'),'payload_bytes':receipt['total_bytes'],'config_present':str((d/'config.json').is_file()).lower(),'tokenizer_files_present':str((d/'tokenizer.json').is_file() and (d/'tokenizer_config.json').is_file()).lower(),'checkpoint_index_status':'PRESENT' if (d/'model.safetensors.index.json').is_file() else 'SINGLE_SHARD_NO_INDEX','weight_shard_count':len(shards),'archive_closure_status':receipt['verification'],'input_authority_status':input_status,'execution_readiness_note':m['notes']})
 write_tsv(out/'MODEL_ASSET_READINESS.tsv',list(asset[0]),asset)
 # Existing Qwen rows (21), then explicitly preserve the three other authority states.
 input_rows=[]
 for r in input_auth:
  if r['model_id'].startswith('Qwen2.5'):
   basis=r['binding_receipt_or_basis'];match=re.search(r'sha256 ([0-9a-f]{64})',basis);binding=match.group(1) if match else 'UNKNOWN_FROM_AUTHORITY_BASIS'
   input_rows.append({'model_variant':r['model_id'],'model_id':auth[r['model_id']]['model_revision'].split('@')[0],'model_revision':auth[r['model_id']]['model_revision'].split('@')[1],'scenario':r['scenario'],'input_class':r['input_class'],'batch':r['batch_size'],'context_tokens':r['prefill_tokens'],'decode_steps':r['decode_tokens'],'token_count':r['prefill_tokens'],'token_payload_sha256':r['payload_sha256'],'binding_sha256':binding,'authority_path':r['payload_path'],'authority_status':r['binding_status'],'notes':r['notes']})
 llama=json.loads((seed/'ADOPTED_LLAMA_INPUT_RECEIPT.json').read_text());s=llama['semantic_identity'];input_rows.append({'model_variant':'Llama-3.2-1B','model_id':s['model_id'],'model_revision':s['model_revision'],'scenario':'S0_TEXT','input_class':s['input_class'],'batch':s['batch_size'],'context_tokens':s['prefill_tokens'],'decode_steps':s['decode_tokens'],'token_count':s['prefill_tokens'],'token_payload_sha256':llama['contract_hashes']['derived_token_ids_sha256'],'binding_sha256':sha256(seed/'ADOPTED_LLAMA_INPUT_RECEIPT.json'),'authority_path':str(seed/'ADOPTED_LLAMA_INPUT_RECEIPT.json'),'authority_status':'FUTURE_ADOPTED_S0_AUTHORITY_NOT_HISTORICAL_RECOVERY','notes':'future-use only; historical frozen input not recovered'})
 for label in ('Qwen3-8B','DeepSeek-V2-Lite'):
  mr=auth[label];input_rows.append({'model_variant':label,'model_id':mr['model_revision'].split('@')[0],'model_revision':mr['model_revision'].split('@')[1],'scenario':'ALL','input_class':'UNKNOWN','batch':'UNKNOWN','context_tokens':'UNKNOWN','decode_steps':'UNKNOWN','token_count':'UNKNOWN','token_payload_sha256':'UNKNOWN','binding_sha256':'UNKNOWN','authority_path':mr['old174_or_recovery_path'],'authority_status':'NO_HISTORICAL_FROZEN_BINDING','notes':'preserved; no new binding created'})
 input_rows.sort(key=lambda r:(r['model_variant'],r['scenario'],r['input_class'],str(r['batch'])))
 write_tsv(out/'MODEL_INPUT_AUTHORITY_INDEX.tsv',list(input_rows[0]),input_rows)
 # Raw7B inventory/residency only reads index and safetensors headers.
 raw=ROOT/'assets/models/qwen2.5-7b-instruct-raw'/'a09a35458c702b33eeacc393d103063234e8bc28';receipt=raw/'MODEL_ARCHIVE_RECEIPT.json';inv=[{**r,'source_shard_sha256_or_receipt_identity':sha256(receipt)} for r in inventory(raw)]
 write_tsv(out/'QWEN25_7B_RAW_CHECKPOINT_INVENTORY.tsv',FIELDS,inv);res=residency(inv);write_tsv(out/'QWEN25_7B_RAW_LAYER_RESIDENCY.tsv',list(res[0]),res);vals=[r['total_decoder_layer_bytes'] for r in res]
 nong={r['tensor_name']:r['exact_tensor_bytes'] for r in inv if r['decoder_layer_id']==''};summary={'decoder_layer_count':len(res),'minimum_decoder_layer_parameter_bytes':min(vals),'median_decoder_layer_parameter_bytes':int(statistics.median(vals)),'maximum_decoder_layer_parameter_bytes':max(vals),'embedding_parameter_bytes':sum(v for k,v in nong.items() if k.startswith('model.embed_tokens.')),'final_norm_parameter_bytes':sum(v for k,v in nong.items() if k.startswith('model.norm.')),'lm_head_output_parameter_bytes':sum(v for k,v in nong.items() if k.startswith('lm_head.')),'tied_embedding_output_configured':'NO (config.json tie_word_embeddings=false)','scope':'parameter residency only; excludes activations, KV, workspace, allocator fragmentation, and kernels'};(out/'QWEN25_7B_RAW_LAYER_RESIDENCY_SUMMARY.json').write_text(canon(summary))
 s2=[r for r in input_rows if r['model_variant']=='Qwen2.5-7B-Instruct raw' and r['scenario']=='S2_TEXT'][0];s2json={'status':'READY_FOR_FUTURE_QUALIFICATION','model_id':s2['model_id'],'exact_model_revision':s2['model_revision'],'canonical_model_path':str(raw),'model_archive_receipt_path':str(receipt),'model_archive_receipt_sha256':sha256(receipt),'checkpoint_index_path':str(raw/'model.safetensors.index.json'),'checkpoint_inventory_sha256':sha256(out/'QWEN25_7B_RAW_CHECKPOINT_INVENTORY.tsv'),'scenario':'S2_TEXT','batch':1,'context_tokens':2048,'decode_steps':32,'input_authority_status':s2['authority_status'],'input_binding_path':str(seed/'INPUT_BINDING_AUTHORITY.tsv'),'input_binding_sha256':sha256(seed/'INPUT_BINDING_AUTHORITY.tsv'),'historical_binding_receipt_sha256':s2['binding_sha256'],'token_payload_path':s2['authority_path'],'token_payload_sha256':s2['token_payload_sha256'],'token_count':2048,'tokenizer_identity_if_recorded':'Qwen/Qwen2.5-7B-Instruct tokenizer files in canonical raw asset'};(out/'QWEN25_7B_RAW_S2_REPLAY_READINESS.json').write_text(canon(s2json))
 contract={'status':'FUTURE_QUALIFICATION_REQUIRED','required':['exact canonical raw7B revision','exact original dtype/runtime semantics','exact frozen S2 input authority','semantic layer streaming reconstructing original hidden states/KV','hash-closed target-layer-state snapshots','exact target layer weights from canonical checkpoint','full-layer replay, not synthetic standalone GEMM','output equivalence against semantic-streaming reference','kernel-signature equivalence','direct GLOBAL MREF plus qualified LDGSTS GLOBAL SOURCE capture required by exact SASS','same-process ADDRESS_CONTEXT for every replay','explicit layer-local claim boundary'],'forbidden_claims':['full-model RTX4080 throughput','full-model global cache/TLB history','cross-layer physical reuse distance','full-resident absolute VA placement'],'execution_not_implemented_here':'Mode A/Mode B GPU execution is forbidden in this CPU-only preparation'};(out/'QWEN25_7B_RAW_FUTURE_REPLAY_CONTRACT.json').write_text(canon(contract))
 # Read-only capture layout audit.
 entries=sorted((ROOT/'catalog/entries').glob('*.json')); rawpaths=[];consistent=True
 for e in entries:
  d=json.loads(e.read_text());p=d.get('raw_path');
  if p:rawpaths.append(p);consistent &= Path(p).is_dir()
 old=ROOT/'raw';new=ROOT/'captures/raw';audit=[{'check':'catalog_entries_with_raw_path','value':str(len(rawpaths)),'status':'PASS'},{'check':'old_raw_path','value':str(old),'status':'PRESENT' if old.is_dir() else 'ABSENT'},{'check':'new_captures_raw_path','value':str(new),'status':'PRESENT' if new.is_dir() else 'ABSENT'},{'check':'overlap_run_ids','value':'NOT_APPLICABLE_NEW_PATH_ABSENT' if not new.is_dir() else 'REQUIRES_ENUMERATION','status':'PASS'},{'check':'capture_redirect_or_migration_receipt','value':'NONE_OBSERVED_FOR_CAPTURE_RAW_LAYOUT','status':'PASS'},{'check':'receiver_script_path_policy','value':'pipeline.py rejects direct /raw/ destination; no current receiver admission-to-old-path writer found','status':'PASS'},{'check':'catalog_paths_exist','value':str(consistent).lower(),'status':'PASS' if consistent else 'FAIL'},{'check':'catalog_physical_consistency','value':'all catalog raw_path directories exist' if consistent else 'missing catalog raw_path directory','status':'PASS' if consistent else 'FAIL'},{'check':'recommendation','value':'NO_ACTION_REQUIRED' if consistent else 'INCONSISTENCY_REQUIRES_REVIEW','status':'READ_ONLY'}];write_tsv(out/'CURRENT_CAPTURE_PATH_AUDIT.tsv',list(audit[0]),audit)
 source=ROOT/'assets/sources/autoawq_kernels';sr=source/'SOURCE_ACQUISITION_RECEIPT.json';source_data=json.loads(sr.read_text());expected_archive_sha256='49304506a87ef74c3a3dd07ddc839d796c25432d2cdd721e1b968977fa78f398';
 if source_data['archive_sha256'] != expected_archive_sha256: raise RuntimeError('FAIL_CLOSED: AutoAWQ archive SHA256 mismatch');tree=source/source_data['source_commit'];gitcmd=['git','-c',f'safe.directory={tree}','-C',str(tree)]
  git_head=subprocess.check_output(gitcmd+['rev-parse','HEAD'],text=True).strip();git_tree=subprocess.check_output(gitcmd+['rev-parse','HEAD^{tree}'],text=True).strip();clean=subprocess.check_output(gitcmd+['status','--porcelain'],text=True).strip()==''
  if git_head!=source_data['source_commit'] or not clean:raise RuntimeError('FAIL_CLOSED: AutoAWQ source identity/cleanliness mismatch')
  manifest={'source_identity':source_data['source_url'],'source_commit_or_tag':source_data['source_commit'],'archive_path':'NO_SEPARATE_ARCHIVE_FILE_EXPOSED; acquisition receipt is canonical archive authority','archive_sha256':source_data['archive_sha256'],'source_receipt_path':str(sr),'source_receipt_sha256':sha256(sr),'source_receipt_archive_relationship':'RECEIPT_ARCHIVE_SHA_PRESENT_AND_SOURCE_COMMIT_MATCHES_CANONICAL_TREE','build_system_files':['setup.py','.github/workflows/build.yaml'],'extension_source_files':sorted(str(x.relative_to(tree)) for x in tree.rglob('awq_ext/*') if x.is_file() and x.suffix in ('.cu','.cpp')),'source_head_tree':git_tree,'source_worktree_clean':clean,'archive_blob_status':'NOT_REHASHED_ARCHIVE_BYTES','expected_python_import_name':['awq_ext','awq_v2_ext','exl_ext','exlv2_ext'],'known_compile_dependencies':['Python >=3.8','setuptools','PyTorch with torch.utils.cpp_extension','CUDA toolkit/nvcc','C++17 compiler','OpenMP/libgomp'],'SM89_arch_flag_or_expected_arch_configuration':'COMPUTE_CAPABILITIES must include 89; setup default includes 75,80,86,87,89,90 and v2 uses 80,86,89,90','expected_wheel_or_so_outputs':['autoawq_kernels wheel','awq_ext*.so','awq_v2_ext*.so','exl_ext*.so','exlv2_ext*.so'],'pytorch_cuda_abi_inputs_that_node109_must_freeze':['python version','torch.__version__','torch.version.cuda','CUDA toolkit/nvcc version','CXX/host compiler version and libstdc++ ABI','COMPUTE_CAPABILITIES=89','GPU driver/runtime'],'notes_on_isolated_environment':'Build only in a fresh node109 isolated environment; do not install into accepted Qwen0/Llama environments; no CUDA build performed on node174-new.'};(out/'AUTOAWQ_KERNELS_BUILD_MANIFEST.json').write_text(canon(manifest))
 (out/'README.md').write_text('# C16 Asset Readiness 174-new V6 R1\n\nCPU-only, metadata-only preparation. Qwen2.5-7B raw is READY_FOR_FUTURE_QUALIFICATION, never FORMAL_ACCEPTED.\n')
 (out/'OPEN_ISSUES.md').write_text('# Open issues\n\n- AutoAWQ source receipt exposes the archive SHA256 but no separately exposed archive file; the canonical source commit matches the receipt. This is nonblocking build metadata only.\n')
 print(json.dumps({'layers':len(res),'min':min(vals),'median':int(statistics.median(vals)),'max':max(vals),'catalog_entries':len(rawpaths)},sort_keys=True))
if __name__=='__main__':main()
