#!/usr/bin/env python3
"""Build non-authority three-lineage review artifacts from raw recomputes."""
from __future__ import annotations
import argparse,csv,hashlib,json
from pathlib import Path
H={'Q30':{'selected':243,'executed':41,'zero':202,'warps':100352,'lanes':3147776},'DEEPSEEK':{'selected':243,'executed':169,'zero':74,'warps':362496,'lanes':11538432},'OLMOE':{'selected':243,'executed':129,'zero':114,'warps':132096,'lanes':4196352}}
RUN={'Q30':'C16R_qwen3-30b-a3b_s2-text_decode_nvbit-warp-mref-shard_s2-dec3-natural-expert21-down_20260917T034400Z_e210c0de5678','DEEPSEEK':'C16R_deepseek-v2-lite_s2-text_decode_nvbit-warp-mref-shard_v23r1-moe-e4-down_20260917T024000Z_b23b23b23b23','OLMOE':'C16R_olmoe-1b-7b-0125-instruct_s2-t2048-d32_decode32_nvbit1771-c16warp1_expert58-down-proj-actual-a_20260922T100810Z_fc0f3cf67edf'}
CAT={'Q30':'80c9d1309fb8d3f15514c9668ac00a6d8839cb6858aca7e347755eed58d2e434','DEEPSEEK':'9ece3f570fbdaa8e026da39bee94c7f15b2c60bf14e292a66f6026104d18d81d','OLMOE':'676422708f865c6b3287998dcde3dd126a469e83d3245bcf00fe11d07b9c1637'}
ACK={'Q30':'f59c9181eb5a6371d93cf648ff15aa771f4af6de04bd9121c9bf2090fb2731f4','DEEPSEEK':'fe4768a91606bbbf89f1b28a897f0a6648fb8e83d3d621093313e03743ec1acf','OLMOE':'9c4d08a960f53acece00dbb3143cba460c22bc638ff4a879833c0e4460b98e39'}
def load(p):return json.loads(Path(p).read_text())
def sha(p):
 h=hashlib.sha256();h.update(Path(p).read_bytes());return h.hexdigest()
def dump(p,x):Path(p).write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
def main():
 a=argparse.ArgumentParser();a.add_argument('--authority',type=Path,required=True);a.add_argument('--out',type=Path,required=True);x=a.parse_args();o=x.out;o.mkdir(parents=True,exist_ok=True)
 r={k:load(o/(k+'_RECOMPUTE.json')) for k in RUN}
 audit={}
 for k,run in RUN.items():
  root=x.authority/'raw'/run; catalog=x.authority/'catalog'/'entries'/(run+'.json'); ack=x.authority/'reports'/'transfer_acks'/(run+'.TRANSFER_ACK.json')
  audit[k]={'run_id':run,'raw_exists':root.is_dir(),'manifest_sha256':sha(root/'RUN_MANIFEST.json'),'catalog_exists':catalog.is_file(),'catalog_sha256':sha(catalog) if catalog.is_file() else None,'catalog_expected':CAT[k],'catalog_matches_expected':catalog.is_file() and sha(catalog)==CAT[k],'ack_exists':ack.is_file(),'ack_sha256':sha(ack) if ack.is_file() else None,'ack_expected':ACK[k],'ack_matches_expected':ack.is_file() and sha(ack)==ACK[k]}
 dump(o/'AUTHORITY_AUDIT.json',{'status':'PASS' if all(v['raw_exists'] and v['catalog_matches_expected'] and v['ack_matches_expected'] for v in audit.values()) else 'FAIL','lineages':audit,'node164_root':str(x.authority)})
 dump(o/'SCOPE_ALIGNMENT.json',{'status':'COMPARABLE_DESCRIPTIVE_ANCHORS','common':['accepted natural-routed BF16 expert down_proj','243 selected static paths','C16WARP1 raw evidence','per-shard-only locality definitions'],'differences':{k:{f:r[k][f] for f in ('semantic_scope','routing_topology','input_width','output_width','weight_shape','weight_bytes')} for k in r},'prohibitions':r['Q30']['prohibited_analyses']})
 hist={}
 for k,v in r.items():
  got={'selected':v['selected_static_count'],'executed':v['executed_static_count'],'zero':v['proven_zero_static_count'],'warps':v['dynamic_warp_records'],'lanes':v['active_lane_events']};hist[k]={m:{'recomputed':got[m],'historical':H[k][m],'equal':got[m]==H[k][m]} for m in H[k]}
 dump(o/'HISTORICAL_REPRODUCTION_CHECK.json',{'status':'PASS' if all(q['equal'] for k in hist.values() for q in k.values()) else 'FAIL','comparisons':hist,'note':'historical values are post-recompute comparison references only'})
 composition={k:{'counts':v['role_event_counts'],'fractions':v['role_fractions'],'weight_input_fraction_delta':v['weight_input_fraction_delta'],'output_fraction':v['role_fractions']['OUTPUT'],'other_fraction':v['role_fractions']['OTHER']} for k,v in r.items()};dump(o/'OBJECT_COMPOSITION_COMPARISON.json',composition)
 static={k:{f:r[k][f] for f in ('selected_static_count','executed_static_count','proven_zero_static_count','failed_excluded_count','executed_fraction','dynamic_warp_records','active_lane_events')} for k in r};dump(o/'STATIC_EXECUTION_COMPARISON.json',static)
 locality={k:{'quantile_definition':v['quantile_definition'],'distributions':v['executed_shard_distributions'],'SUM_OF_PER_SHARD_UNIQUES':v['SUM_OF_PER_SHARD_UNIQUES']} for k,v in r.items()};dump(o/'LOCALITY_DISTRIBUTION_COMPARISON.json',locality);dump(o/'ROLE_CONDITIONED_COMPARISON.json',{k:v['role_conditioned'] for k,v in r.items()})
 impl={'Q30':{'durable_function':r['Q30']['static_implementation']['function_evidence'],'relation':'internal cuBLAS BF16 gemvx template parameter 7'},'DEEPSEEK':{'durable_function':r['DEEPSEEK']['static_implementation']['function_evidence'],'relation':'internal cuBLAS BF16 gemvx template parameter 6'},'OLMOE':{'durable_function':r['OLMOE']['static_implementation']['function_evidence'],'relation':'actual-JIT variant A; current raw selector lacks full gemvx template text'},'deepseek_olmoe_exact_template_relation':'NOT_RECOMPUTABLE_FROM_CURRENT_RAW_SELECTOR','shared_operator_semantics':'BF16 expert down_proj anchors','interpretation':'independent model lineages; runtime implementation-family coupling is possible and exact DeepSeek/OLMoE template identity is unresolved from current durable raw selector'};dump(o/'IMPLEMENTATION_RELATION.json',impl)
 patterns=[{'id':'weight_input_balance','class':'T3','basis':'all three weight/input fractions are equal within each recompute; each is approximately one half','threshold':'absolute weight-input fraction delta <= 0.001'},{'id':'output_smallness','class':'T3','basis':'all output fractions below 0.001','threshold':'output fraction < 0.001'},{'id':'other_zero','class':'T3','basis':'OTHER fraction exactly zero in all three','threshold':'OTHER == 0'},{'id':'selected_coverage','class':'T3','basis':'243 selected paths in all three; not static-code equivalence'},{'id':'executed_fraction','class':'L1','basis':'Q30 41/243 differs materially from DeepSeek 169/243 and OLMoE 129/243'},{'id':'implementation_coupling','class':'U','basis':'Q30 durable template=7, DeepSeek durable template=6; OLMoE raw selector lacks full template text'}];dump(o/'PATTERN_CLASSIFICATION.json',{'definitions':{'T3':'three model lineages observed','T2':'two lineage only','L1':'lineage specific','U':'unresolved'},'patterns':patterns})
 with (o/'THREE_LINEAGE_COMPARISON.tsv').open('w',newline='') as f:
  w=csv.writer(f,delimiter='\t');w.writerow(['metric','Q30','DEEPSEEK','OLMOE'])
  for m in ('selected_static_count','executed_static_count','proven_zero_static_count','executed_fraction','dynamic_warp_records','active_lane_events','weight_input_fraction_delta') :w.writerow([m]+[r[k][m] for k in RUN])
  for role in ('WEIGHT','INPUT','OUTPUT','OTHER'):w.writerow([role+'_fraction']+[r[k]['role_fractions'][role] for k in RUN])
 interp='''# Scientific interpretation\n\n## What is common across all three accepted model lineages\n\nAcross the three accepted independent model lineages, the natural-routed expert `down_proj` anchors show a shared descriptive weight/input-balanced, output-small, OTHER-zero event composition under the observed cuBLAS gemvx deployments.\n\n## What differs materially\n\nExecuted static coverage, event-scale distributions, and per-shard spatial footprints differ; Q30 has materially fewer executed paths. Equal selected count is not static-code equivalence.\n\n## What may be caused by shared kernel implementation rather than MoE semantics\n\nQ30 and DeepSeek durable static maps show BF16 internal gemvx variants 7 and 6 respectively. OLMoE is conditioned on actual-JIT variant A, but its accepted raw selector lacks the full template text. Thus model lineages are independent, while runtime implementation-family coupling is present/possible; exact DeepSeek/OLMoE template identity is unresolved from current raw selector.\n\n## What this does and does not justify studying next\n\nThis is descriptive, per-shard-only evidence. It does not establish matched-input causality, cross-process VA relations, cache/TLB causality, or a universal MoE law. Candidate follow-up questions require ChatGPT/user review.\n''';(o/'SCIENTIFIC_INTERPRETATION.md').write_text(interp)
 dump(o/'FINAL_DECISION.json',{'status':'C16_THREE_INDEPENDENT_MODEL_LINEAGE_MOE_CONSUMER_V1_PASS','implementation_coupling_caveat':impl['interpretation'],'no_new_experiment_authorized':True})
 dump(o/'NEXT_STEP_AUTHORIZATION.json',{'status':'REVIEW_REQUIRED','new_capture_authorized':False,'new_tlb_cache_mechanism_authorized':False,'candidate_questions':['whether exact OLMoE gemvx template evidence can be durably exported','whether matched-input design is scientifically justified']})
if __name__=='__main__':main()
