#!/usr/bin/env python3
from __future__ import annotations

import subprocess
import sys
import time

sys.dont_write_bytecode = True
from a20_a23_latpc_vm_lib import NESTED_ROOT, REPORT_DIR, ensure_dirs, latest, read_csv, rel, stage_report, ts, write_csv

AHM = NESTED_ROOT / "src/abstract_hardware_model.cc"
GPU_SIM = NESTED_ROOT / "src/gpgpu-sim/gpu-sim.cc"


def gate_allows() -> bool:
    gate = latest("A20C_latpc_implementation_gate_*.csv")
    if not gate:
        return False
    return any(r["gate_item"] == "source_implementation_allowed" and r["status"].lower() == "true" for r in read_csv(gate))


def patch_once(path, needle, replacement) -> bool:
    text = path.read_text()
    if replacement in text:
        return False
    if needle not in text:
        raise RuntimeError(f"needle not found in {path}: {needle[:80]}")
    path.write_text(text.replace(needle, replacement, 1))
    return True


def main() -> int:
    ensure_dirs()
    stamp = ts()
    start = time.time()
    start_iso = time.strftime("%Y-%m-%dT%H:%M:%S%z")
    matrix_csv = REPORT_DIR / f"A21B_latpc_hook_integration_matrix_{stamp}.csv"
    modified_csv = REPORT_DIR / f"A21B_latpc_modified_source_files_{stamp}.csv"
    report = REPORT_DIR / f"A21B_latpc_shadow_vm_hooks_stats_{stamp}.md"
    if not gate_allows():
        status = "PASS_DESIGN_ONLY"
        blocker = "A20C gate did not allow implementation"
        matrix = []
        modified = []
    else:
        patch_once(AHM, '#include "cuda-sim/ptx-stats.h"\n', '#include "cuda-sim/ptx-stats.h"\n#include "gpgpu-sim/latpc_shadow_vm.h"\n')
        observe_needle = "  // Calculate memory accesses generated by this warp\n"
        observe_repl = '''  if (space.get_type() != shared_space && space.get_type() != sstarr_space) {
    unsigned long long latpc_shadow_addrs[MAX_WARP_SIZE];
    unsigned latpc_shadow_count = 0;
    for (unsigned thread = 0; thread < m_config->warp_size; thread++) {
      if (!active(thread)) continue;
      new_addr_type addr = m_per_scalar_thread[thread].memreqaddr[0];
      if (addr != 0 && latpc_shadow_count < MAX_WARP_SIZE)
        latpc_shadow_addrs[latpc_shadow_count++] = addr;
    }
    latpc_shadow_vm_observe_warp_addresses(0, m_warp_id, pc, 0,
                                           latpc_shadow_addrs,
                                           latpc_shadow_count);
  }

  // Calculate memory accesses generated by this warp
'''
        patch_once(AHM, observe_needle, observe_repl)
        patch_once(GPU_SIM, '#include "l2cache.h"\n', '#include "l2cache.h"\n#include "latpc_shadow_vm.h"\n')
        print_needle = '  printf("latpc_functional_mechanism_enabled = 0\\n");\n\n'
        print_repl = '  printf("latpc_functional_mechanism_enabled = 0\\n");\n  latpc_shadow_vm_print_stats(statfout);\n\n'
        patch_once(GPU_SIM, print_needle, print_repl)
        status = "PASS_WITH_WARNINGS"
        blocker = "none"
        matrix = [
            {"hook_name": "latpc_shadow_vm_observe_warp_addresses", "component": "address_observation", "source_path": "gpu-simulator/gpgpu-sim/src/abstract_hardware_model.cc", "source_symbol": "warp_inst_t::generate_mem_accesses", "exactness": "WARP_INSTRUCTION_LEVEL", "data_available": "effective per-lane first address; SM id approximate 0; event cycle", "behavior_affecting": "no", "risk": "effective address not proven true VA", "notes": "default disabled; returns void"},
            {"hook_name": "latpc_shadow_vm_print_stats", "component": "stats_print", "source_path": "gpu-simulator/gpgpu-sim/src/gpgpu-sim/gpu-sim.cc", "source_symbol": "gpgpu_sim::gpu_print_stat", "exactness": "PRINT_ONLY", "data_available": "raw counters", "behavior_affecting": "no", "risk": "extra output only", "notes": "keeps A18 sentinel stats"},
        ]
        modified = [
            {"path": "gpu-simulator/gpgpu-sim/src/gpgpu-sim/latpc_shadow_vm.h", "repo": "nested", "modification": "add shadow VM helper", "lines_estimate": "330", "behavior_change_expected": "no", "notes": "header-only"},
            {"path": "gpu-simulator/gpgpu-sim/src/abstract_hardware_model.cc", "repo": "nested", "modification": "add include and observe hook", "lines_estimate": "14", "behavior_change_expected": "no", "notes": "void side model"},
            {"path": "gpu-simulator/gpgpu-sim/src/gpgpu-sim/gpu-sim.cc", "repo": "nested", "modification": "add include and print hook", "lines_estimate": "2", "behavior_change_expected": "no", "notes": "print-only"},
        ]
    write_csv(matrix_csv, matrix, ["hook_name", "component", "source_path", "source_symbol", "exactness", "data_available", "behavior_affecting", "risk", "notes"])
    write_csv(modified_csv, modified, ["path", "repo", "modification", "lines_estimate", "behavior_change_expected", "notes"])
    diffstat = subprocess.getoutput(f"git -C {NESTED_ROOT} diff --stat")
    stage_report(report, "A21B LATPC Shadow VM Hooks And Stats", status, start_iso, start, ["python3 scripts/accelsim/a21b_latpc_shadow_vm_hooks_stats.py", "git -C gpu-simulator/gpgpu-sim diff --stat"], [".local_reports/A20C_latpc_implementation_gate_*.csv"], [rel(matrix_csv), rel(modified_csv), rel(report)], blocker, ["No Regularity Detector/LATC/LATP implemented.", "Observe hook is side-effect-free and default disabled."], "## Nested Diffstat\n\n```\n" + diffstat + "\n```")
    print(f"A21B status: {status}")
    print(f"A21B report: {rel(report)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
