NVCC ?= nvcc
ARCH ?= sm_86
OUT ?= route_b_memory_event_inject.o
all: $(OUT)
$(OUT): route_b_memory_event_inject.cu route_b_memory_event_common.h
	$(NVCC) -Xptxas -astoolspatch --keep-device-functions -Xcompiler -fPIC -arch=$(ARCH) -O3 -c $< -o $@
