NVBIT_HOME ?=
NVCC ?= nvcc
# Retry570 is an RTX3090 (SM86); CUDA 12.4 requires the ``sm_`` spelling.
ARCH ?= sm_86
OUT ?= retry570_targeted_memory_tool.so

ifeq ($(strip $(NVBIT_HOME)),)
$(error NVBIT_HOME must identify the hash-closed NVBit 1.8 release root)
endif

NVCC_LIB = -L $(subst bin/nvcc,lib64,$(shell which $(NVCC) | tr -s /))
INCLUDES = -I$(NVBIT_HOME)/core
LIBS = -L$(NVBIT_HOME)/core -lnvbit $(NVCC_LIB) -lcuda -lcudart_static -ldl -lrt -lpthread

all: $(OUT)

$(OUT): retry570_targeted_memory_tool.cu $(NVBIT_HOME)/core/libnvbit.a
	$(NVCC) -std=c++17 -D_FORCE_INLINES -Xptxas -astoolspatch --keep-device-functions -Xcompiler -fPIC -arch=$(ARCH) -O3 $(INCLUDES) $< $(LIBS) -shared -o $@

clean:
	rm -f $(OUT)
